### ISSUE TITLE
add 'frameify' argument to profileApply

### ISSUE THREAD

**Issue by brownag** [ncss-tech/aqp#111]
**Purpose:** facilitate handling of complex `profileApply` results by cleanly converting to data.frame, with _idname_ as column. Provides basic functionality for processing a list, with each list element containing a numeric vector with the values of several attributes -- essentially a single "row" or "record" in a data frame. 

In this example the vector contains the calculated top and bottom depth of PSCS for each pedon.

```
frameify <- function(l, colnames=NULL) {
  res <- as.data.frame(cbind(names(l), do.call('rbind', l)), row.names = FALSE)
  colnames(res) <- colnames
  return(res)
}

site(f) <- frameify(profileApply(f, estimatePSCS, simplify=FALSE), 
                    colnames = c(idname(f), "calc_pscstop", "calc_pscsbot"))
```

The above could be even further simplified by building the `frameify` result option into profileApply. Setting `frameify=TRUE` would override the default of `simplify=TRUE`. 

```
site(f) <- profileApply(f, estimatePSCS, frameify=TRUE, 
                    colnames = c(idname(f), "calc_pscstop", "calc_pscsbot"))
```

With not too much extra accounting this could be further extended to determine whether a site _or horizon_ level attribute is returned. 

For instance, if a hypothetical function returned a _matrix_ of values -- with one row/record for each pedon HORIZON --  `profileApply` could return a result that merges cleanly into the horizons slot by supplying both _idname_ and _hzidname_.

```
horizons(f) <- profileApply(f, somePedotransferFunction, frameify=TRUE, 
                    colnames = c(idname(f), hzidname(f), "newhzlevelattribute1", "newhzlevelattribute2"))
```

**Comment by dylanbeaudette** [comment]
I like this. Could we also enforce "safe" merging of site / hz attributes by checking to see if one of the appropriate IDs are in the results? In other words, all functions provided to profileApply would have to be specific to an ID.

**Comment by dylanbeaudette** [comment]
Pending a couple more tests, this is just about ready to go. Testing on 10k profiles:
 * 60 seconds using a single chunk
 * 14 seconds using chunk.size=100
 * 12 seconds using chunk.size=100 and pre-allocation of temporary lists

**Comment by brownag** [comment]
Thanks for catch with stringsAsFactors being true by default. b4c171f -- issue closed
