### ISSUE TITLE
SoilProfileCollection object overhaul

### ISSUE THREAD

**Issue by dylanbeaudette** [ncss-tech/aqp#114]
The `SoilProfileCollection` class has been the corner-stone of the `aqp` package for nearly 10 years, and workhorse for USDA-NRCS pedon / component data analysis for nearly 8. There have been important updates to the internal structure over the years to accommodate diagnostic features, restrictions, and better merging of site / horizon level attributes via unique IDs. There are still many outstanding problems that the current implementation cannot solve:

 * sub-setting / indexing  of large `data.drame` objects is slow
 * no simple way to shuffle the ordering of an SPC once it has been build
 * linkage between `@horizons`, `@site`, and `@sp` is based on row-order

Three routes forward:
 1. `SoilProfileCollection` is a list of `SoilProfile` objects, each a singular version of the current class. Data would only be stacked into a `data.frame` at analysis-time. Sub-setting, re-ordering, and `profileApply`-like operations would scale much better based on past tests. It is not clear if the extra split/stack operations would outweigh these gains.

 2. Replace `@horizons`, `@site`, an maybe `@diagnostic` and `@restriction` with `data.table` objects. These slots would be [keyed](https://cran.r-project.org/web/packages/data.table/vignettes/datatable-intro.html) to `idname(SPC)` and `@horizons` would have an additional key set to `hzidname`. The use of indexed / sorted data structures should improve speed. The reshaping / aggregation methods would help drop dependencies (#79) and improve speed / functionality of `slab` (#3, #60). Note that `data.table` operations are automatically parallelized.

3. Following `sf` use a `data.frame` that contains `list` columns to model the various 1:many relationships (c/o Pierre).

**Comment by pierreroudier** [comment]
I wonder if we could get inspiration from what `sf` did, and create column-lists that can store some of that stuff.

**Comment by dylanbeaudette** [comment]
After a quick re-write of `slice()` using `data.table` principles, the speed-up (600x faster) and code reduction (40% number of lines), I'm leaning towards option **2**.

**Comment by pierreroudier** [comment]
@dylanbeaudette Note that (2) and (3) are not exclusive: 

https://www.r-spatial.org/r/2017/11/13/perp-performance.html
https://github.com/SymbolixAU/spatialdatatable

**Comment by dylanbeaudette** [comment]
The 2.0 release of aqp addresses most of the original intent: performance, scalability, `data.table` support, migration to `sf`, and safer indexing, and more.
