### ISSUE TITLE
hzName() and hzName<- getter/setter for dataset specific horizon designation attribute

### ISSUE THREAD

**Issue by brownag** [ncss-tech/aqp#116]
Create getter/setter for a new slot `@hzdesgnname`

This would make the name/hzname/hzdesgn argument to several functions (e.g. estimateSoilDepth, getArgillicBounds) no longer necessary. Default would be set by SPC constructor -- could be NULL. fetchXXX functions will set the value of the slot accordingly for known datasources (NASIS, SDA, KSSL, etc).  Will be manually entered via `hzName<-` in the case of data sets created from flat files, etc.

The current heuristics for finding hzdesgn looks for "name" in the column -- e.g. in plotSPC -- this is fine, and could be extended further to look for typical horizon designations in the data itself (rather than just horizon name) -- if unambiguous and unique values are found within peiid could set automatically,

Also consider `@texclname` -- could be used in lieu of argument `getArgillicBounds()` and would be useful for designing additional horizon-centric analyses down the line

The goal would be to emulate horizonDepths()-type functionality -- removing ambiguities of how data are specified from different database sources. Side issue: some functions still include "top" and "bottom" arguments that can be replaced by using horizonDepths()

**Comment by dylanbeaudette** [comment]
Great idea. Do you want to try and sneak this into aqp 1.19, or perhaps into the next CRAN release. I'd like to get aqp to CRAN this week if possible.

**Comment by brownag** [comment]
Yes, I could probably put this together either today or tomorrow.

**Comment by brownag** [comment]
This is done. Wound up finding a silly oversight that meant the slot contents weren't being transferred after `[`-subsetting (82cbd7d). I have beefed up some tests to catch this sort of thing going forward (429cd07)
