### ISSUE TITLE
switch to sf for spatial data?

### ISSUE THREAD

**Issue by dylanbeaudette** [ncss-tech/aqp#117]
Given the coming changes in PROJ/GDAL and retirement of `sp`/`rgeos` (#109), it is a good time to consider updating the way in which spatial data are stored within the `SoilProfileCollection` object. Furthermore, coordinate reference system definitions are moving away from proj4 notation. This means that we will need to update interfaces to getting / setting CRS of SPC objects.

I'm not 100% sure, but switching `@sp` (`Spatial Points`) to `@spatial` such that it contains sf-type objects. These could be points, lines, polygons, or even a mixture of these types. Opening-up the possibility of associating polygons with records in a `SoilProfileCollection` is an interesting idea.

**Comment by brownag** [comment]
As much as I love sp / rgeos, it is time to migrate to sf. I like where you are going with being able to associate other spatial data types with SPC.

**Comment by pierreroudier** [comment]
I've made the switch for my personal workflows, and I'm not looking back.

Even better, I think this is an opportunity to simplify the SPC: essentially what was the `@sp` slot can now be a column in the `@site` slot:

```
library(aqp)
library(sf)
library(sp)

# Example: sp1
data(sp1)
depths(sp1) <- id ~ top + bottom
site(sp1) <- ~ group

# Create a set of random locations, in EPSG:4326
sp1@sp <- sp::SpatialPoints(coords = cbind(runif(9), runif(9)), proj4string = sp::CRS('+init=epsg:4326'))

# Adding the spatial locations as a simple feature column in the @site slot
sp1@site$geom <- sf::st_as_sfc(sp1@sp)
sp1@site
st_crs(sp1@site$geom)
```

**Comment by dylanbeaudette** [comment]
Interesting idea. Lets see where this takes us. I like the idea of incredible flexibility, but worried about losing the consistency that S4 enforces (sometimes to a fault!).

**Comment by pierreroudier** [comment]
Bumping up this issue -- just wondering whether we could simply support the `sf` objects when creating a SPC. 

At the moment, `depths(df) <- id ~ top + bottom` fails if `df` is a `sf`: it needs to be converted to a `data.frame` using `sf::st_set_geometry(df, NULL)`. 

However, the beauty of `sf` objects is that they are storing geometries as a special column, but just a column nonetheless. So arguably we could create a SPC, even if a `sf` object has this specific column.

**Comment by brownag** [comment]
This is a good idea @pierreroudier -- this is something I have thought of but never tried. I assume this is the error you bump into:

``` r
library(aqp)
#> This is aqp 1.25
library(sf)
#> Linking to GEOS 3.9.0, GDAL 3.2.1, PROJ 7.2.1

data(sp4)
sp4$x <- runif(nrow(sp4))
sp4$y <- runif(nrow(sp4))

sf4 <- st_as_sf(sp4, coords=c("x","y"))

depths(sf4) <- id ~ top + bottom
#> Error in (function (classes, fdef, mtable) : unable to find an inherited method for function 'depths<-' for signature '"sf"'
```

Do you know of a way around the fact that the following fails? This is the mechanism that we use to get around not having specific `depths<-` dispatched for the different data.frame subclasses is by using `setOldClass`. This makes everything properly  inherit. In theory this is what we would need to do to support `sf` same way we do `tbl_df` and `data.table`.

```
>   setOldClass(c("sf", "data.frame"))
Error in setOldClass(c("sf", "data.frame")) : 
  inconsistent old-style class information for “sf”; the class is defined but does not extend “data.frame” and is not valid as the data part
```

See also #169 for some rambling thoughts on simplifying the sp slot and providing conversion methods to sp and sf. I don't know enough off hand about the specifics of how sf and sfc relate to data.frame and list, respectively -- but i will investigate!

**Comment by pierreroudier** [comment]
I suspect a (possibly ugly) workaround would be to set up a `depth<-` method for `sf`?

**Comment by brownag** [comment]
That is what I was thinking, certainly could dispatch on "sf" instead of "data.frame".  

And we would need to do something like that -- because presumably if you had an `sf` object you wanted to pass to `depths<-` it would have the spatial data denormalized out as horizon-level variables, presumably -- which would be a pretty weird existing sfc geom in most cases, no? Essentially a duplicated multipoint for each site?

**Comment by brownag** [comment]
Though, I am very excited about prospects of {wk} rct representation of soil profile horizons -- so geom in the horizons slot is not totally out there, at least to me!

**Comment by dylanbeaudette** [comment]
Interesting concept: @pierreroudier do you have a simple use case in mind + example data / code?

**Comment by pierreroudier** [comment]
@brownag: Yes, as a first step I was thinking we could try and store the geom at horizon level. The I thought it might not be so silly as we could even try and see because there is the Z axis for depth... not sure about that one. Otherwise we could implement a simple test that if a column is a `sfc` then this is denormalised and goes automatically to the `@site`. 

@dylanbeaudette: No example code as I'd have to spend a bit more time on this, but:

```
library(aqp)
library(sf)

# Load example data containing coordinates
data(ca630)

# Convert to sf
ca_site_sf <- st_as_sf(ca630$site, coords = c('lon', 'lat'), crs = 4326)
ca_site_sf

# Convert to SPC -- this errors at the moment
depths(ca_site_sf) <- user_site_id ~ cntrl_depth_to_top + cntrl_depth_to_bot
```

**Comment by brownag** [comment]
OK @pierreroudier, sorry for deluge but you hit on something I've been thinking a lot about. I welcome your thoughts.

I like the idea of having a model for "point" depths with XYZ POINT. For certain types/styles of sampling this may be more appropriate than assuming samples are representative of a (potentially large) rectangular block e.g. a morphologic horizon. 

For the SPC, the authoritative information on the Z dimension comes from the `depths<-` formula call and the horizon data columns containing those values. The SPC "integrity" logic in large part relies on that top-depth ordering (currently) and the relative positions of top and bottom depths of adjacent layers. 

### Would this be best done via an alternate method for `depths<-`, or a different function e.g. `sf_as_spc()`?

We could make wrapper that processes "point" horizon data into something resembling a SPC. There are different "methods" out there that I have seen/read about for doing this depending on what folks are working with for inputs and to some degree what their "soils background" is (perhaps) and scope of sampling

No aqp methods currently "look" for that Z dimension information in e.g. an `sfc` column, but they _could_ -- even if for the sole purpose of converting into a "standard" tabular SPC, with id, top, bottom, unioned spatial geometry for XY available in `@site` or `@sp` etc. 

### Is the SPC just a temporary "container" for these more detailed spatial data, or does the geometry become integrated into algorithms and models that use the object?

However, my stumbling block with horizon geometry is this -- if/how to keep the geometry object (if it is in horizons) in sync with the SPC object. Most of this is taken care of when dealing with subsets etc. but various transformations occur that would require either dropping geometry or rebuilding it from depths.

In the future, the columns containing 'top' and 'bottom' depths could be dynamically realized _from_ geometry... and the `depths<-` route would be for standard data.frame-like input (probably not including "sf"). 

## On paths forward...

{wk} has a lot of vctrs-based classes that seem really appropriate in this application, and this aligns pretty well with what I have been thinkin'. Specifically `wk_xyz` in your suggested case, v.s. my `wk_rct` suggested above. These are alternate, not equivalent but _related_, representations of "profile geometry."

The wk vectors can store CRS as an attribute and can be readily converted to `sf`, serialized to well-known binary or text, and processed. And they work great being created on-the fly from list or data.frame objects. In my view, the future of the `@sp` slot is essentially a simple `data.frame`, and we could use something like `wk` to convert it to `sf` objects -- possibly representing site, horizon or other generalizations of the geometry. 

I think there is value in providing some way to easily convert `sf` objects of defined structure(s) to SPC, but would need to see more on the benefits of incorporating `sfc` _internally_ -- as opposed to something like a `wk` rect or even just a data.frame containing the X,Y,Z data in `@sp`.

**Comment by pierreroudier** [comment]
First -- I'm not a huge fan of using a XYZ POINT to represent horizon data. It is usually a surface or a volume be sampled, a better approximation I think is to think of a line going down from a XY POINT, and intervals representing horizons *along* that line. 

Some thoughts on the points you raised:

**Would this be best done via an alternate method for depths<-, or a different function e.g. sf_as_spc()?**

I think the beauty of `sf` objects are that they "feel" like a `data.frame`, and allows to do spatial without to disrupt one's workflow to much, so my gut feeling would be to just add another `depth<-` method.

**Is the SPC just a temporary "container" for these more detailed spatial data, or does the geometry become integrated into algorithms and models that use the object?**

Keeping those geometries in sync raise a good point. I had to do a fair bit of interval calculations for [this paper](https://www.mdpi.com/2072-4292/12/18/2872), and ended up using a `sf` representation for the site location, along with `Interval` objects ([from the `intervals` package](https://cran.r-project.org/web/packages/intervals/vignettes/intervals_overview.pdf)) for the horizon depths to do operations on depth intervals.

**On paths forward...**

Completely agree on your view regarding the `@sp` slot -- it's old-school, and using some form of geometry column makes much more sense, is easier, and more modern. Haven't looked too much at `wt` so far.

**Comment by brownag** [comment]
@pierreroudier RE: XYZ POINT me neither -- but I wish my suspicions about it were backed up by some solid geometric "standards".

I suspect that despite the fact that "sf" feels like a data.frame -- it is not _quite_ a data.frame in all the important ways. Thus the issue with `setOldClass`. It likely wouldn't just be `depths<-` that needs wrappers -- but all sorts of code that currently cleanly dispatches to data.frame that would then need some extra "handling" to allow the sf data.frames to persist in the SPC.

Since I suggested {wk} as an avenue here is my take on on a possible path towards a lightweight sf implementation that is "SPC friendly". Please don't pay any attention to method names as i thought all of 30 seconds on those. Doesn't solve all of the problems, but it is cheap and takes the route of just using the `sfc` in regular data.frame rather than a "sf" data.frame inside the SPC.

```r
########################################################################################################
# wk data.frame geometry "decorator"
########################################################################################################

#' Experimental: Make `wk` vector geometry "granules"
#'
#' @param object a `data.frame` containing data that can (currently) be with two POINT geometries, or one POINT and one RECT.
#' @param coords named character; coordinates to create geometry from: default a=`x`, b=`y`, c=`z`, d=`m`, where coordinates refer to "X", "Y", "top" and "bottom" depth ("Z"), respectively. In theory, other paired "Z" coordinates are possible. e.g. mean and standard deviation, thickness and midpoint, etc.
#' @param type geometry type to use for horizons (`XY` (top/bottom or other) or `RCT` (unit width))
#' @param crsxy passed to `wk::xy`; default: `wk::wk_crs_auto()`
#' @param crsz passed to `wk::xy` or `wk::rct`; default: `wk::wk_crs_auto()`
#'
#' @return a `data.frame` containing two `wk` vectors: `"XY"` (as `wk_xy`) and `"Z"` (as `wk_xy` or `wk_rct`)
#'
granulate <- function(object,
                      coords = c(a = "x", b = "y", c = "z", d = "m"),
                      type = c("xy", "rct"),
                      crsxy = wk_crs_auto(),
                      crsz = wk_crs_auto()) {

  type <- match.arg(type, c("xy", "rct"))
  stopifnot(inherits(object,'data.frame'))
  stopifnot(coords %in% colnames(object))

  # X,Y geom (1:1 with "site")
  WKXY <- wk::xy(object[[coords[["a"]]]],
                 object[[coords[["b"]]]],
                 crs = crsxy)

  # Z geom (RECT or POINT)
  WKVCT <- switch(type,
                  "rct" = wk::rct(#RCT: xmin ymin xmax ymax
                    -0.5, object[[coords[["c"]]]], 0.5, object[[coords[["d"]]]], crs = crsz),
                  "xy" = wk::xy(#XY: top, bottom  / thickness, midpoint / mean, standard deviation etc.
                    object[[coords[["c"]]]], object[[coords[["d"]]]], crs = crsz))


  cbind(as.data.frame(object), data.frame(geometry = WKXY, hzgeometry = WKVCT))
}

########################################################################################################
# SOILPROFILECOLLECTION METHODS
########################################################################################################
# define SPC methods for accessing geom columns stored as wk vector(s) in data.frame slots of the SPC

#   - not sure that non-atomic vectors will survive being data.table-ified
#   - may need to be stored in a dedicated data.frame slot (e.g. @sp, or @geom) not subject to `aqp_df_class`
#   - and perhaps "magically" made to appear in `horizonNames`/`horizons()` etc. as needed

`sfCoords<-` <- function(object, value) {
  # this is just a dummy horizon->site geometry "promote" function -- not the "real" deal
  newsite <- object[[value]][match(profile_id(object), horizons(object)[[idname(object)]])]
  object[[value]] <- NULL
  # print(newsite)
  object[[value]] <- newsite
  return(object)
}

# access site geometry column as sfc
siteGeom <- function(object)
  if(inherits(object, 'SoilProfileCollection') && "geometry" %in% siteNames(object))
    wk_handle(site(object)$geometry, wk::sfc_writer())

# access horizon geometry column as sfc
horizonGeom <- function(object)
  if(inherits(object, 'SoilProfileCollection') && "hzgeometry" %in% horizonNames(object))
    wk_handle(horizons(object)$hzgeometry, wk::sfc_writer())

########################################################################################################
# EXAMPLE
########################################################################################################

library(wk)
library(aqp)

data("sp4", package = "aqp")

# make some fake X/Y data to add to sp4
uid <- unique(sp4$id)
uxy <- data.frame(id = uid, east = runif(length(uid)), north = runif(length(uid)))
sp4 <- merge(sp4, uxy, all.x = TRUE, sort = FALSE)

# make the geometry "granules"
sp4rct <- granulate(sp4, c(a="east", b="north", c="top", d="bottom"), type = "rct")
sp4 <- granulate(sp4, c(a="east", b="north", c="top", d="bottom"))

depths(sp4) <- id ~ top + bottom
depths(sp4rct) <- id ~ top + bottom

# this contains 2 wk vectors
horizons(sp4)

# this "promotes" the XY geom to site
sfCoords(sp4) <- "geometry"

# these are sfc geometry; only needs wk!
siteGeom(sp4)
horizonGeom(sp4)

# XY plot method
plot(sp4$geometry)

# RCT plot method, e.g. all profile's rct vector (note, inverted need positive depth "CRS" to look right)
plot(sp4rct$hzgeometry)
#                  e.g. just one
plot(sp4rct[1,]$hzgeometry)

### using sf

# convert site slot directly to sf data.frame
sf::st_as_sf(site(sp4))

# convert horizon slot directly to sf data.frame
sf::st_as_sf(horizons(sp4))
```

**Comment by dylanbeaudette** [comment]
Lots of great ideas here, moving on to #272 where we will be moving to `sf`, and providing simpler methods for keeping track of spatial metadata. Coercion functions can take care of the heavy lifting.
