### ISSUE TITLE
replacement method for horizons

### ISSUE THREAD

**Issue by dylanbeaudette** [ncss-tech/aqp#119]
Given the potential for SPC corruption, it might be a good idea to require an argument to `horizons<-` that specifies: "perform a LEFT JOIN" vs. "replace what is in `@horizons`".

**Comment by brownag** [comment]
I think this would indeed make the operations a bit more explicit.

I wonder whether the LEFT JOIN is actually the more common operation of the two -- and therefore, for simplicity, _replacing horizons_ has either an argument or even a separate setter. 

If horizons() was relegated to the left-join behavior, it wouldn't be as bad to throw errors or warnings when the join would be messed up by the RHS. If a separate function or argument was used for the replacement behavior, that would be the prevailing use internally (at least within aqp).

Just thoughts. I will be pondering how to improve the horizon merge set this weekend.

**Comment by brownag** [comment]
I am wondering if an additional setter is required, or whether slot(spc, 'horizons') is sufficient for the replacement operation. Outright replacing the slots of an S4 object is a pretty low-level operation, in my opinion.

 In ec9175be8058648fe08b687d66ae70a3a619f9ef and 778e3a142e0c9f026932773046f8a987a90f8254 I successfully converted essentially all the aqp internal/doc uses of `horizons<-` to just use `slot(...,'horizons')`. Several could use the setter. I certainly see no harm in adding a "convenience" setter ala `replaceHorizons<-`

In https://github.com/ncss-tech/soilDB/commit/26dbd290e985a40b7ebc32373ec82719ed6300fc I show an external use of the slot replacement where a convenience method might be nice. That said, refactoring said code to produce a suitable LEFT JOIN RHS (just needs `idname()`) would get rid of the `plyr::join`. This same case happens in many other places where external joins and slot replacement could be replaced with `horizons<-`

**Comment by brownag** [comment]
If we knew that `horizons<-` would always behave as LEFT JOIN, we could issue messages and relax constraints to protect from inadvertent SPC corruption.

```
library(aqp)
library(soilDB)

data(loafercreek)
h <- horizons(loafercreek)

# horizons<- LEFT JOIN condition #2 is that there are new columns
h$foo <- 1:nrow(h)*2

# we did some modification before the RHS got re-sorted
horizons(loafercreek) <- h[rev(1:nrow(loafercreek)),]

# six horizons, correct values since LEFT JOIN behavior triggered
horizons(loafercreek[1,])
```

```
# try again, with no new data we find things messed up
data(loafercreek)
h <- horizons(loafercreek)

# attempt horizons<- with unchanged horizon data
# this was always the behavior of horizons<- as long as the other couple criteria are met
horizons(loafercreek) <- h[rev(1:nrow(loafercreek)),]
```

```
# reversed horizons and index
loafercreek[1,]

data(loafercreek)

h <- horizons(loafercreek)

# historic behavior of horizons<- is also reproduced with slot<-
slot(loafercreek, 'horizons') <- h[rev(1:nrow(loafercreek)),]

# reversed horizons and index
loafercreek[1,]
```

**Comment by dylanbeaudette** [comment]
Thanks for modifying all replacement instances of `horizons<-` to use `slot`. Overall, I'd like `horizons<-` to behave like `site<-`: it is far more common (as far as I can tell) for operations external to the S4 guts to use the LEFT JOIN interface vs. total replacement. I distinctly recall shuddering the first time I wrote a replacement-style `horizons<-`.  Therefore, how about we do this:

   * `horizons<-` expects at least one unique key supporting a LEFT JOIN
      + the setter ensures that nrow(hz.data) doesn't change 
      + the setter ensures that at least 1 suitable key is present
      + the user is responsible for making a left-hand table that doesn't contain spurious keys0
   * `replaceHorizons` is a wrapper around `slot(x, 'horizons') <-` that checks:
      + all relevant IDs and depth columns are in place
      + extended attributes such as texture class are present (?)
      + conservation of profile IDs: none gained / lost

**Comment by brownag** [comment]
@dylanbeaudette I'll implement these ASAP -- thanks for giving a clear list of requirements. Should be straightforward to do

**Comment by pierreroudier** [comment]
Here's an idea (untested): we could include the name of the relevant key as an attribute of the SPC, which can then be used to do the join when using `horizons<-`:

```
atttr(spc, "horizon_key") <- "hid" 
```

**Comment by brownag** [comment]
> * `replaceHorizons` is a wrapper around `slot(x, 'horizons') <-` that checks:
>   
>   * all relevant IDs and depth columns are in place
>   * extended attributes such as texture class are present (?)
>   * conservation of profile IDs: none gained / lost

https://github.com/ncss-tech/aqp/commit/a4562bbc1323d7792897f1a7692219ea5a7fced0

adds replaceHorizons<- setter
