### ISSUE TITLE
Problems with sp 1.4-0 and soilDB/sharpshootR

### ISSUE THREAD

**Issue by rsbivand** [ncss-tech/aqp#123]
Because of ongoing changes to resolve  PROJ/GDAL breaking changes, a new **sp** is being submitted to CRAN, to be followed by a new **rgdal**, using WKT instead of Proj strings (**sf** is doing the same). The new CRAN warnings raised when submitting **sp** can be resolved in both cases by raising **rgdal** to Imports:, and adding `import(rgdal)` to NAMESPACE.

We do not know why this is happening, but of all the CRAN revdeps of **sp**, these two are the only ones to see regressions. Once the new **rgdal** is out and deployed, you may be able to see whether **rgdal** can be moved back to Suggests:.

**Comment by brownag** [comment]
Interesting, thank you for the heads-up. Would be interesting to see why ours regressed while none of the other reverse dependencies did...

**Comment by rsbivand** [comment]
I saw similar odd warnings when a package importing the **rgdal** namespace loaded as **rgdal** was being re-installed, so it could be something transient. If CRAN gets back to you, you have my suggestion for a fix, a bit invasive, but may go away when the next **rgdal** is released. Since I see that your packages are looking at transiting to **sf**, this might also be a way forward (but it also depends on **raster**/**stars** and whether **raster** is still needed.

**Comment by rsbivand** [comment]
The problem may be resolved after a logic bug in **sp** was spotted by Brian Ripley today. Probably does not need intervention from you.

**Comment by dylanbeaudette** [comment]
Thanks.
