### ISSUE TITLE
should aqp::slice preserve hzname and texture class?

### ISSUE THREAD

**Issue by brownag** [ncss-tech/aqp#126]
Currently one needs to explicitly include variable names for the `@hzdesgncol` & `@hztexclcol` slots, and then manually set their values to preserve the information in the `slice()` result.

This issue is simply to point out that these are commonly-used contextual information that we could make easier to pass through to the `slice`-d result. 

We could: 

1.  Pass through the slot values from parent SPC to sliced SPC where those values are also present in the RHS of formula 

2. Add an argument to transfer slots (without having to specify the var in formula) -- this would apply to all cases that were feasible -- obviously not the unique horizon IDs though

```
library(aqp)
library(soilDB)
data(loafercreek)

slicepc <- slice(loafercreek, 0:200 ~ clay + hzname + texture)

hzdesgnname(slicepc) <- "hzname"
hztexclname(slicepc) <- "texture"

g1 <- glomApply(slicepc, estimatePSCS)

plot(g1[1:10,])
```

**Comment by dylanbeaudette** [comment]
Interesting development, and now quite obvious: as we move "important" hz-level attributes to slots this kind of thing will happen. I think that the contents of slots should transcend most operations. If it is important enough to live in a slot, then an operation like `slice` should include it.

That said, we have to be conservative with these special attributes: each adds additional overhead to any function that re-creates an SPC.

**Comment by brownag** [comment]
I agree. And I pushed to put those contents in slots-- because I think they are that important. These attributes, I argue, provide fundamental _pedologic_ context. I plan to fully implement these slots wherever it will be expedient to the user (without causing undue overhead)

**Comment by brownag** [comment]
Also, I think perhaps that I like option #3 of the two I gave above. 

3. `slice` should transfer "optional" pedologic context slots _that are set_ without having to specify the slot variable name in formula

**Comment by dylanbeaudette** [comment]
I prefer your option 3. 

Do you think that it would make sense to keep a checklist or convenience function for propagation of specialized slots?

**Comment by brownag** [comment]
It probably would be worthwhile to have a centralized way of handling these things to facilitate maintenance. I'd have to take some more time to ponder how it would be generalized.

**Comment by dylanbeaudette** [comment]
I'll start a template / checklist here: https://github.com/ncss-tech/aqp/wiki/Wrangling-SPC-Objects
