### ISSUE TITLE
aqp::matchSPC

### ISSUE THREAD

**Issue by brownag** [ncss-tech/aqp#130]
magrittr-friendly `match` for SPCs.

Purpose: easily propagate subsetting operations from one profile collection to another. This is especially helpful when doing calculations on a `glom` result that then need to be propagated into filtering logic for the parent SPC.

Approximate code:

```
matchSPC <- function(spc_in, spc_out) {
  i1 <- idname(spc_out)
  i2 <- idname(spc_in)
  
  if(i1 != i2)
    warning("match: profile ID names do not match (",i1,":",i2,")", call. = FALSE)
  
  idx <- which(site(spc_out)[[idname(spc_out)]] %in% spc_in[[idname(spc_in)]])
  
  if(!length(idx))
    idx <- 0
  
  return(spc_out[idx,])
}
```

Example usage: Glom _thickest_ horizon in 0-15cm interval, filter subset to get pedons with clay loam texture (in thickest horizon 0-15cm), then use `aqp::matchSPC` to get the full profiles (not just `glom` result) that met those criteria.

```
library(aqp)
library(soilDB)
library(magrittr)

f <- fetchNASIS()

f.sub <- f %>% 
  glomApply(.fun=function(x) return(c(0,15)), modality="thickest") %>%
  filter(texcl == "cl") %>%
  matchSPC(f)

plot(f.sub)
```

**Comment by dylanbeaudette** [comment]
Thanks. Seems like a good idea. Is the main purpose to remove the use of temporary indexing variables?

**Comment by brownag** [comment]
I would say it is more than just removing temporary indexing variables.

It would not be simpler to return only IDs. I think that would sortof defeat the whole purpose of glomApply. This new syntax is keeping SoilProfileCollections as the central data object in analysis -- not derivatives thereof.

**Comment by brownag** [comment]
To expand on that -- the following logic is too complicated to have to re-use all the time.

There are several possible stumbling blocks for new users -- most importantly the duplication of idname in site and horizon slots -- which will produce erroneous results -- not an error.

`which(site(spc_out)[[idname(spc_out)]] %in% spc_in[[idname(spc_in)]])`

**Comment by dylanbeaudette** [comment]
OK, I think that I understand now: the main idea is to abstract that enormous `which` incantation. Is the code committed to MASTER? My only concern: what what is  the result of `SPC[0, ]`? I've never tried / tested this before. 

```r
Object of class SoilProfileCollection
Number of profiles: 0

Horizon attributes:
 [1] id      name    top     bottom  color   texture sand    silt    clay    Fe      Mn      C       pH      Db      hzID   
<0 rows> (or 0-length row.names)
```

Cool, an empty SPC. I didn't think that would work. I really like abstracting low-level operations (e.g. making safer / simpler code) so that as you say the SPC remains the central object of analysis. Thanks for all of the hard work.

**Comment by brownag** [comment]
I found myself in a situation yesterday where I needed this function, but have not yet incorporated it to master because even when I created it I had strong second thoughts about the details

Sometimes you want to do a calculation on depth nterval from every profile... Some of which won't complete. Dropping IDs with `union` only tells you that one or more inputs were NA. 

I suppose I am not convinced that this above is the best solution -- it seems like it was a workaround of how `union` handles NA inputs. Appropriate topologic checks and warnings are issued by e.g. glom but those profiles "disappear"... Which can pose some issues for getting the results of an analysis back into the parent SPC and/or generating indexes that can safely pull it off.

This should work. No new function needed:

```
f.sub <- f %>% 
  glomApply(.fun=function(x) return(c(0,15)), modality="thickest") %>%
  filter(texcl == "cl")

# full profiles with dominant 0-15cm cl texture
f <- filter(f, profile_id(f) %in% profile_id(f.sub))
```

**Comment by brownag** [comment]
The broader case where a site or horizon attribute is calculated over the glom interval could be handled by simply just transferring value after filter.
