### ISSUE TITLE
integrate Rosetta parameter centroids

### ISSUE THREAD

**Issue by dylanbeaudette** [ncss-tech/aqp#131]
Find these files in `misc/example-data/rosetta`.

These are mean and SD VG parameters from the Rosetta model, buy soil texture class. Combined with reasonable AWC estimates, these would be a fine LUT to have built-in to {aqp}.

**Comment by brownag** [comment]
Me-from-5-years-ago would be over the moon about this update.

**Comment by brownag** [comment]
I have recently refined my AWC lookup table (based on the RO2 guide -- which uses textural class and OM class) code for more routine use in R -- it probably could use some more refinement -- but I have it set up to run off low-rv-hi values for DMUs in development -- very handy.

**Comment by dylanbeaudette** [comment]
Any chance that we can put that table into a helper function? I had bigger plans for the VG centroids, e.g. simulation of ranges based on the mean / SD, but haven't quite finished that aspect. Was thinking that it would be nice to get some rough AWC and water retention estimates based on texture class. Mostly for prototyping vs. *real* estimation.

**Comment by brownag** [comment]
I've done some of that simulation -- I would be interested to see what you come up with on that front.

Yes, I agree it would be good to be able to have some different estimate methods in there for comparison purposes. Can do,  it wont take much for me to package it up for use in aqp.

**Comment by dylanbeaudette** [comment]
TODO at some future point: finish documentation of the VG model viz and simulation of envelopes.

**Comment by dylanbeaudette** [comment]
![image](https://user-images.githubusercontent.com/624277/84988223-7c2d2c00-b0f6-11ea-8866-3d532859d2f4.png)
