### ISSUE TITLE
roxygen2 documentation for all S4 methods

### ISSUE THREAD

**Issue by brownag** [ncss-tech/aqp#139]
Many important internal methods are currently aliased to a single page --- and others are not explicitly documented other than in examples.

As I have worked to refine various structures of the dual site-horizon table model of the SoilProfileCollection object I will be implementing full documentation for the S4 methods that define the workings of the SPC.

This is part of a broader effort to migrate all documentation to roxygen (#28). It is hoped that the examples that follow demonstrate the value of that approach.

**Comment by brownag** [comment]
Visual aid (example)

![image](https://user-images.githubusercontent.com/20842828/84670840-7ad3e780-aedb-11ea-9607-e1f8a0a1a2df.png)

**Comment by dylanbeaudette** [comment]
Thanks. Any tips on converting long .Rd content into roxygen-style documentation? For example, the slab manual page.

**Comment by brownag** [comment]
I have been doing 'em manually -- there might be a way to reverse engineer. I can pull together a default template for S4 methods. I have also worked out a general scheme for methods that have both a normal and a `<-` version.

I would be happy to do the slab/slice methods using the same method i have done so far. But so far have stuck to stuff previously aliased to SPC-utils or coercion.

**Comment by brownag** [comment]
In general -- it is better to let Roxygen to do the heavy lifting. The main things that need to be lifted from the .Rd are the description/details, argument descriptions and examples. The rest is pretty boilerplate. In particular, autogenerated usage sections are far superior to hardcoded.
