### ISSUE TITLE
aesthetics: function for growing bottom-most horizons when bottom depth missing or too thin

### ISSUE THREAD

**Issue by dylanbeaudette** [ncss-tech/aqp#173]
Case in point, the OSDs are used for demonstrations but many of the bottom-most R and Cr horizons have a missing bottom depth. The `parse-OSD` post-processing step adds 1cm of depth to these horizons, but that isn't enough when trying to make "aesthetically reasonable" sketches. I'd rather not force this on the world as part of the OSD interpretation, rather, offer a simple function that operations on SPCs to "grow" the bottom-most horizon when it matches a pattern and is `< x thickness`.

![image](https://user-images.githubusercontent.com/624277/101083716-d06f7f80-3561-11eb-88bd-5c20087f9afb.png)

```r
library(aqp)
library(soilDB)
library(sharpshootR)

x <- c('Tunbridge', 'Winooski', 'Covington', 'Londonderry', 'Woodstock')
s <- fetchOSD(x)

SoilTaxonomyDendrogram(
  s, width = 0.3, plot.depth.axis = FALSE, 
  name.style = 'center-center', cex.names = 0.66, 
  hz.depths = TRUE, y.offset = 0.33, 
  scaling.factor = 0.02, dend.width = 2
)

# sort profiles in plot according to original order
o <- match(profile_id(s), toupper(x))

par(mar = c(0, 0, 0, 0))
plotSPC(
  s, width = 0.3, plot.depth.axis = FALSE, 
  name.style = 'center-center', cex.names = 0.66, 
  hz.depths = TRUE, 
  plot.order = o, scaling.factor = 1.2
)
```

Something like this:
   * using the horizon designation (set / guessed column name)
   * iterate over profiles
   * find affected horizon records
   * test thickness, and if horizon is at the bottom of the stack
   * increase lower depth accordingly

**Comment by brownag** [comment]
I will say that this is a useful thing -- I have written hacky routines to modify the horizon slot inplace to snap all R horizons to 200cm for many plots, including ones with OSDs. 

However, I think that thickness of Cr and other lower gradational horizons is more important to be based on data -- so I am a bit cautious. For OSDs and things that are more conceptual, it makes sense to have a robust enough system for handling different cases. I think of some instances like the Dunstone series whose OSD description of Cr does not cover the whole series control section (minimum +25cm from contact)

**Comment by brownag** [comment]
![image](https://user-images.githubusercontent.com/20842828/101087430-0c591380-3567-11eb-90d4-0beabc732ddf.png)

**Comment by dylanbeaudette** [comment]
Thanks for the ideas / examples. This is for aesthetic purposes only: the manual page will emphatically make this point. I'm thinking that this is intentionally invoked and not some kind of automatic / magical process.

**Comment by brownag** [comment]
To the aesthetic end -- it would be nice to be able to "paint" the bedrock using same/similar patterns. Cr is this, R is that, etc. I dunno whether an additional, optional site-level categorical variable for "parent material origin" would be pushing it... :)

**Comment by dylanbeaudette** [comment]
After discussion all around, I'd suggest that the horizon depth "fixes" currently in soilDB be abstracted into this new function which would accomplish the following:
 * replace `NA` in missing lower horizon depths → offset via argument
 * replace bottom depths when `top == bottom` → offset via argument
 * extend lower horizon depths when bottom-most horizon is too thin  → threshold and offset via argument

Possible function names: `fixMissingHzDepths`, `repairMissingDepths`, ???

**Comment by brownag** [comment]
I think that the three cases you identified would be fine to cover in an aqp function. `NA` bottom most depths and equal depths etc _generally_ do not arise from spurious joins, but are intrinsic to e.g. the input horizon data.

I want highlight fact that data model and query specific (`JOIN`-related) data quality issues are probably just as common as "bad data"  in terms of producing logic errors in need of "fixing."

Therefore the distinction of what should be done in soilDB versus aqp is not trivial. It falls along lines of whether it is more for aesthetics or mostly-uncontroversial ways of filling in gaps versus identifying tabular data problems that manifest in depth logic errors.

**Comment by dylanbeaudette** [comment]
Another use-case for "fixing" NAs in horizon depths: the new version of `slice` cannot tolerate horizons out of order or depth logic errors. #115

**Comment by dylanbeaudette** [comment]
Moved non-aesthetic content / ideas to #198.

**Comment by dylanbeaudette** [comment]
Turns out these OSDs have since been updated:

![image](https://github.com/ncss-tech/aqp/assets/624277/6adf1e6d-6b45-4b16-9db9-12d56a692ada)

... and `fillHzGaps()` gets one close to the desired result.
