### ISSUE TITLE
Allow for MD style authoring of Rd content

### ISSUE THREAD

**Issue by dylanbeaudette** [ncss-tech/aqp#184]
MD-style authoring of manual pages is super convenient, but will break a lot of documentation.

https://cran.r-project.org/web/packages/roxygen2/vignettes/rd-formatting.html

Enable via toggling:
```
# in DESCRIPTION
Roxygen: list(markdown = FALSE)
```

**Comment by brownag** [comment]
I am all for this, and would like a large scale re-work of existing roxygen and static .Rds to also include moves to using `@importFrom` so we can generate the NAMESPACE automatically.
