### ISSUE TITLE
Empty SPC with placeholder ID, top, bottom depths

### ISSUE THREAD

**Issue by dylanbeaudette** [ncss-tech/aqp#214]
While working on some QA stuff, I found it necessary (helpful) to have a placeholder SPC when something like an OSD was not available. A simple function did the trick, but before adding to {aqp} wanted to get feedback.

I suspect that a more general form would be important for adding "fake" horizons to horizon-less profiles. I don't have time to implement right now. Seems to work fine on all `data.frame` subclasses.

```r
#' @title Fake a Single Profile `SoilProfileCollection` from Template
#'
#' @param x template `SoilProfileCollection`
#' @param fakeID a new, fake ID
#' @param top a new top depth
#' @param bottom a new bottom depth
#'
#' @return `SoilProfileCollection` containing a single, fake profile
#' @export
#'
#' @examples
#' 
#' # simplest case, use a SPC
#' data("jacobs2000")
#' fakeSPC(jacobs2000)
#' 
#' # convert to SPC with data.table internals
#' x <- jacobs2000
#' aqp_df_class(x) <- 'data.table'
#' x <- rebuildSPC(x)
#' 
#' fakeSPC(x)
#' 
#' # convert to SPC with tibble internals
#' x <- jacobs2000
#' aqp_df_class(x) <- 'tibble'
#' x <- rebuildSPC(x)
#' 
#' fakeSPC(x)
#' 

fakeSPC <- function(x, fakeID = 'MISSING', top = 0, bottom = 150) {
  
  # use the first profile / horizon
  # as template
  fake <- x[1, 1]
  
  # critical IDs and depths
  idn <- idname(x)
  hzid <- hzidname(x)
  htb <- horizonDepths(x)
  hzname <- hzdesgnname(x)
  
  # min required for @site
  s <- site(fake)
  # set all columns to NA
  s[] <- NA
  # ID
  s[[idn]] <- fakeID
  
  # min required for @horizons
  h <- horizons(fake)
  # set all columns to NA
  h[] <- NA
  
  # IDs
  h[[idn]] <- fakeID
  h[[hzid]] <- fakeID
  
  # depths
  h[[htb[1]]] <- top
  h[[htb[2]]] <- bottom
  
  # hzname if possible
  if(hzname != '') {
    h[[hzname]] <- ''
  }
  
  # re-pack
  fake@site <- s
  fake@horizons <- h
  
  return(fake)
}
```

**Comment by dylanbeaudette** [comment]
Any thoughts @brownag , @smroecker , @jskovlin , @pierreroudier ?

**Comment by pierreroudier** [comment]
@dylanbeaudette Could you please elaborate with a real-world use case? Is the idea to simulate "potential" SPC from an existing one? Which parts would be simulated?

**Comment by dylanbeaudette** [comment]
This is quite possibly the least interesting function in {aqp}: no simulation, just an empty SPC for those cases when you need to have something. Better approaches?

```r
library(aqp)
library(soilDB)

# expecting an SPC, but there is no OSD
o <- fetchOSD(soils = 'junk')

# other, related data
data("jacobs2000")
x <- jacobs2000

# fail-safe when `o` isn't available
if(is.null(o)) {
  o <- fakeSPC(x, bottom = max(x))
}

# wanting to plot together, as part of some automated report etc.
plotMultipleSPC(
  list(o, x), 
  group.labels = c('OSD', 'Data'), 
  bracket.base.depth = max(x) + 10
)
```

**Comment by brownag** [comment]
If I understand correctly, this new function is to get around the fact that it is not "easy" to add a site to an existing SPC if that site has no horizons (i.e. it is a placeholder)

I think you are missing 2 things:
1) user could specify arbitrary idname, which at least could affect the SPC id+top depth order under normal circumstances
2) rebuild and reset default `hzID` because you added horizon and potentially changed the internal order

Here is an example with `jacobs2000`
```r
library(aqp, warn=FALSE)
#> This is aqp 1.29

# other, related data
data("jacobs2000")
x <- jacobs2000

newdata <- site(x)[1, , drop = FALSE]
newdata[] <- NA
newdata[[idname(x)]] <- "foo"
x@site <- rbind(x@site, newdata)

newhzdata <- horizons(x)[1,]
newhzdata[] <- NA
newhzdata[[idname(x)]] <- "foo"
newhzdata[,horizonDepths(x)] <- c(0, 150)
x@horizons <- rbind(x@horizons, newhzdata)

checkHzDepthLogic(x)
#>     id valid depthLogic sameDepth missingDepth overlapOrGap
#> 1 92-1  TRUE      FALSE     FALSE        FALSE        FALSE
#> 2 92-2  TRUE      FALSE     FALSE        FALSE        FALSE
#> 3 92-3  TRUE      FALSE     FALSE        FALSE        FALSE
#> 4 92-4  TRUE      FALSE     FALSE        FALSE        FALSE
#> 5 92-5  TRUE      FALSE     FALSE        FALSE        FALSE
#> 6 92-6  TRUE      FALSE     FALSE        FALSE        FALSE
#> 7 92-7  TRUE      FALSE     FALSE        FALSE        FALSE
#> 8  foo  TRUE      FALSE     FALSE        FALSE        FALSE
spc_in_sync(x)
#>   nSites relativeOrder valid
#> 1   TRUE          TRUE  TRUE

# re-set hzID
horizons(x)$hzID <- as.character(1:nrow(x@horizons))
hzidname(x) <- "hzID"
```

Note that  I put it together in order... the following is required if not "in sync"

```r
# this applies id+top depth order (NB custom ID requires re-sort)
x <- rebuildSPC(x)
#> using `hzID` as a unique horizon ID
```
```r
plot(x, color="clay")
```

![](https://i.imgur.com/zga4lO8.png)

**Comment by dylanbeaudette** [comment]
> EDIT: I guess I assumed you wanted your fake SPC to be put into the template. I realize that is a more complicated use case perhaps than what you proposed.

Yes. This function makes no attempt to create a "safe" candidate for later `combine()` with a real SPC. That would be a fine extension (ensuring that the fake SPC could be merged back into the template `x`), but not a requirement at this time.

**Comment by brownag** [comment]
My above post as you agree takes it a step beyond what you are asking. My only remaining questionsare semantic. Why not "emptySPC" or "templateSPC" or something, since we do not truly support the 0-length SPC (and arguably can't under current data model)? I guess I just don't like the word "fake" though I know what it means.

**Comment by dylanbeaudette** [comment]
Good question and ideas: `emptySPC` makes more sense, I'll use that instead. Thanks.

**Comment by brownag** [comment]
I guess I do have one other question: for your simpler use case, why not just create a data.frame and promote with `depths<-`? 

For me, using the template SPC for things other than column names might lead to unexpected problems with slot replacement. Why do it if there is no plan to do some sort of combination of the SPCs? 

All you need in simpler case is a data.frame with the ID column name and depths. You probably don't _want_ to copy other slots etc. associated with first profile. Your case only replaces `@site` and `@horizons`

**Comment by dylanbeaudette** [comment]
Closing this, as there are simple ways to make an 'empty', single-profile SPC. With `quickSPC()` and templates, it doesn't get much simpler than:

```r
x <- 'empty:NODATA,151,NA-'
s <- quickSPC(x)
plotSPC(s, name.style = 'center-center', cex.names = 1, plot.depth.axis = FALSE, hz.depths = TRUE)
```
