### ISSUE TITLE
USFS-inspired pedon sketches

### ISSUE THREAD

**Issue by dylanbeaudette** [ncss-tech/aqp#219]
Idea and example c/o Colby Brungard.

![image](https://user-images.githubusercontent.com/624277/113177056-fa7c3a00-9201-11eb-9928-2441ac63ad0d.png)

This style of labeling is already possible, but abstraction would help with conditional use of `\n`: depends on horizon thickness, label size, device size, etc..

The ragged bottom could be added when profiles are deeper than `max.depth`.

First cut:
```r
library(aqp)

data("rowley2019")

# not so interesting, these all share the same texture
rowley2019$texture <- ssc_to_texcl(sand = rowley2019$Sand, clay = rowley2019$Clay)

## TODO: condition the use of \n on horizon thickness:
##       thin horizons use name : texture : pH

# composite horizon ID
rowley2019$hz.label <- sprintf(
  "%s\n%s: %s", 
  rowley2019$name, 
  rowley2019$texture, 
  round(rowley2019$pH, 1)
)


par(mar = c(0, 0, 0, 2))

plotSPC(
  rowley2019, 
  width = 0.25, 
  name.style = 'center-center', 
  name = 'hz.label', 
  cex.names = 0.85
)
```

**Comment by brownag** [comment]
+1 for ragged bottom, also would be nice to be able to specify a vector of the depths for individual pedons

**Comment by dylanbeaudette** [comment]
Making progress.

![image](https://user-images.githubusercontent.com/624277/233194134-6faf8cf9-ac97-464c-a666-a88d4b82ac28.png)

Still TODO:

- [ ] truncate profiles according to new argument
- [ ] flag truncated profiles
- [ ] test

**Comment by dylanbeaudette** [comment]
Conditional ragged bottoms
![image](https://user-images.githubusercontent.com/624277/233275356-7c38a08e-7264-451b-8f32-17b70990367a.png)

**Comment by dylanbeaudette** [comment]
That is pretty close.  I'll open another issue if I have time to craft a legend.

![image](https://user-images.githubusercontent.com/624277/233479929-55d72298-cac1-48f9-8fe4-4b42e04f6eff.png)


```r
library(aqp)
library(soilDB)

data("rowley2019")

# not so interesting, these all share the same texture
rowley2019$texture <- ssc_to_texcl(sand = rowley2019$Sand, clay = rowley2019$Clay)

## TODO: condition the use of \n on horizon thickness:
##       thin horizons use namne : texture : pH

# composite horizon ID
rowley2019$hz.label <- sprintf(
  "%s\n%s: %s", 
  rowley2019$name, 
  toupper(rowley2019$texture), 
  sprintf("%.1f", rowley2019$pH)
)

# flag truncated profiles
site(rowley2019)$rb <- c(TRUE, FALSE) 

par(mar = c(0, 0, 0, 2))

plotSPC(
  rowley2019, 
  width = 0.25, 
  name.style = 'center-center', 
  name = 'hz.label', 
  cex.names = 0.85,
  color = 'Ca_exch',
  max.depth = 50,
  raggedBottom = 'rb'
)

```
