### ISSUE TITLE
parseMunsell performance upgrade

### ISSUE THREAD

**Issue by dylanbeaudette** [ncss-tech/aqp#230]
Not sure if this is related to changes in #221 or policy changes on our government machines (more scanning). Likely related to working with tiny `data.frames`. Most of the REGEX code (stringr) can be vectorized.

Currently vectors ~10k elements require 10 seconds to process.

**Comment by dylanbeaudette** [comment]
After vectorizing (pending PR):

```
Unit: milliseconds
 expr        min         lq       mean     median         uq        max neval
  1e3     6.4113     6.4113     6.4113     6.4113     6.4113     6.4113     1
  1e4    62.5150    62.5150    62.5150    62.5150    62.5150    62.5150     1
  1e5   557.1182   557.1182   557.1182   557.1182   557.1182   557.1182     1
  1e6  6508.7192  6508.7192  6508.7192  6508.7192  6508.7192  6508.7192     1
  1e7 68181.0054 68181.0054 68181.0054 68181.0054 68181.0054 68181.0054     1
```

**Comment by pierreroudier** [comment]
@dylanbeaudette looks much better, was it an issue in my original code?

**Comment by dylanbeaudette** [comment]
Totally your fault! Just kidding. I'm not really sure: it was probably a combination of:

* more advanced string parsing via REGEX
* working with too many, tiny `data.frame` objects

**Comment by pierreroudier** [comment]
Ha! It's a fair assumption to blame my super poor regex game, to be honest!

**Comment by dylanbeaudette** [comment]
I found this while working on the [color mixing tutorial](https://ncss-tech.github.io/AQP/aqp/mix-colors.html#232_Spectral_Differences:_Adjacent_Chips) where I was abusing `parseMunsell` to process 2.8 million combinations. So: I found some inefficient code while performing a very inefficient analysis.
