### ISSUE TITLE
vectorization of perturb vs. new function?

### ISSUE THREAD

**Issue by dylanbeaudette** [ncss-tech/aqp#233]
I'm on the fence here: add some "safe" vectorization to `perturb` vs. a brand-new function. 

 * safe vectorization is always nice, but adds complexity
 * a simpler `perturb` is simpler to verify / optimize
 * a new function like `bootstrapProfile()` could include additional simulation: colors, properties, etc. without having to add complexity to `perturb`
 * ???

I do not have specific requirements in mind other than keeping aqp as organized as possible.

```r
library(aqp)
library(sharpshootR)
library(cluster)

# example data
data(sp4)
depths(sp4) <- id ~ top + bottom

# boundary variation parameter
horizons(sp4)$bdy <- 4

# iterate over profiles and simulate morphology
bootstrapProfile <- function(x, n, ...) {
  
  # SPC -> list of 1-element SPCs
  s <- split(x, f = profile_id(x))
  
  # iterate over list and simulate morphology
  res <- lapply(s, function(i) {
    
    # safe IDs
    pID <- profile_id(i)
    ids <- sprintf("%s-%03d", pID, 1:n)
    
    # simulate
    p <- perturb(i, id = ids, ...)
    return(p)
  })
  
  # flatten
  res <- combine(res)
  
  # TODO:  further simulation of properties / colors / etc.
  
  return(res)
}

# simulate three of each soil
b <- bootstrapProfile(sp4, n = 3, boundary.attr = 'bdy', min.thickness = 2)

# compare
d <- profile_compare(b, vars = c('ex_Ca_to_Mg', 'CEC_7'), max_d = 50, k = 0)
dd <- diana(d)

# viz
plotProfileDendrogram(b, dd, scaling.factor = 1.5, y.offset = 4, color = 'ex_Ca_to_Mg', width = 0.3, name.style = 'center-center', plot.depth.axis = FALSE, hz.depths = TRUE, cex.names = 0.65, col.label = 'Exchangeable Ca:Mg')
```

**Comment by brownag** [comment]
I think it would be great to have several functions that work with perturbed results and simulate various properties.

However, regarding question of "new function" versus "vectorize perturb" the answer is clear to me. I think `perturb()` itself absolutely should be vectorized. I the short term we could take split/apply approach as you did in `bootstrapProfile()` but in the long run I have some optimizations in mind that should make the whole approach significantly faster. I have it working provisionally, just not yet with all of the options that are currently supported in `perturb()` / backwards compatible with `sim()`

**Comment by dylanbeaudette** [comment]
Excellent. Yeah: that `split`→`lapply` habit is a tough one to break. Great for prototyping but not efficient with complex S4 objects.

**Comment by dylanbeaudette** [comment]
Any progress on this front? I've got some use cases coming up soon. I like the idea of vectorized `perturb`. Backwards compatibility with `sim` is not a priority, esp. since it has now been deprecated for a while.

**Comment by brownag** [comment]
Yes, the remaining broken test I believe was with the `sim()` compatibility / "thickness-based perturbation" when multiple profiles are involved. I think I can probably sort it out without too much more effort. Will create draft PR to close this issue, thanks for the reminder to push up the local branch i was working on
