### ISSUE TITLE
Always retain metadata, even with explicit subsetting as in dice()

### ISSUE THREAD

**Issue by dylanbeaudette** [ncss-tech/aqp#263]
Should functions that operate return SPC objects always return full metadata such as `hzdesgnname`? I have no preference either way, but preservation seems like a good strategy no matter the implied subsetting.

**Comment by brownag** [comment]
https://github.com/ncss-tech/aqp/issues/126

**Comment by brownag** [comment]
I still prefer the "always retain metadata" (if set and result is an SPC) option
