### ISSUE TITLE
Create "fetchOSD" sample dataset for use in examples/vignette

### ISSUE THREAD

**Issue by brownag** [ncss-tech/aqp#267]
Currently the vignette uses

```r
library(soilDB)
x <- fetchOSD(c('appling', 'cecil', 'bonneau'))
```
as some sample code to demonstrate how to plot SPCs. 

I think that if we need to use OSD data for this example (not sure we do), it should be converted to an internal dataset that does not require a request to a remote data source or suggesting a package that itself imports {aqp}.

**Comment by dylanbeaudette** [comment]
I've wanted an example from `fetchOSD` for a while now, and I agree, the main aqp vignette should not depend soilDB or network resources. Adding one now.

**Comment by brownag** [comment]
A note that the soilColorSignature() tests also rely on fetchOSD(). Noticing some intermittent results lately (likely related to SoilWeb server upgrades?)
