### ISSUE TITLE
fillHzGaps(p) error with single profile, single horizon

### ISSUE THREAD

**Issue by dylanbeaudette** [ncss-tech/aqp#301]
Error will manifest in `dice(..., fill = TRUE)`. 

Occurs in `fillHzGaps()` here:
```r
bad.idx <- which(h[[htb[2]]][lag.idx] != h[[htb[1]]][lead.idx]
                   & h[[idn]][lag.idx] == h[[idn]][lead.idx])
```

Example.
```r
library(aqp)

p <- data.frame(id = 1, top = 0, bottom = 100, p = 5)
depths(p) <- id ~ top + bottom

pp <- duplicate(p, times = 2)

# error
fillHzGaps(p)

# no error
fillHzGaps(pp)
```

Given the corner-case nature, as far as I can tell, consider a simple test for `length(x) == 1 && nrow(x) == 1`, immediately returning the original SPC.

**Comment by brownag** [comment]
I pushed a small fix for the indexing in https://github.com/ncss-tech/aqp/commit/480b7f62c229e9e1dc39a546da323d5184835577 so the single-horizon SPC is covered.

> Given the corner-case nature, as far as I can tell, consider a simple test for `length(x) == 1 && nrow(x) == 1`, immediately returning the original SPC.

I think you don't want a short-circuit here. Consider a slightly more complex (but still single horizon) example:

```r
library(aqp)
p <- data.frame(id = 1, top = 25, bottom = 100, p = 5)
depths(p) <- id ~ top + bottom
fillHzGaps(p, to_bottom = 200)
```

**Comment by dylanbeaudette** [comment]
Excellent! Thanks for the fix and checking that a simpler solution wasn't a good idea. Looks good to me.
