### ISSUE TITLE
hz_segment just accepts aqp_df_class == "data.frame" - may be not clearly documented ...

### ISSUE THREAD

**Issue by rolhar** [ncss-tech/aqp#320]
Dear aqp-Team!

aqp is a great project! 

For me it seems like hz_segment just accepts SoilProfileCollection objects with aqp_df_class == "data.frame". E.g. with data.table I get an error ...

I think other classes are at least excluded by line 191 (https://github.com/ncss-tech/aqp/blob/9a3624015f33d7cc9dd144b46a5d1906807602b4/R/segment.R#L191) !?

May be it is worth to explicitly add this restriction to the documentation???

Or did I miss something?

Thank you very much!

(I could add a reprex if appreciated ...!)

**Comment by brownag** [comment]
Thank you for reporting this @rolhar.

It is great to hear you are utilizing the data.table variety of SoilProfileCollection objects!! In general we want all functions to at least be able to "handle" the data.table inputs--even if sometimes that may require casting to data.frame internally; there are probably other cases that don't quite work right so feel free to report them if you find them.

This instance results from using the "list" type column subsetting with a data.table from the horizon slot. We can handle the column subset as intended with the object type stored in the SPC using an internal aqp function (`aqp:::.data.frame.j()`) so you get a data.table-SPC as a result.

For example, after a023abb8 this works as expected:

``` r
library(aqp)
#> This is aqp 2.1.0
data("jacobs2000")
aqp_df_class(jacobs2000) <- "data.table"
jacobs2000 <- rebuildSPC(jacobs2000)
#> using `hzID` as a unique horizon ID
res <- hz_segment(jacobs2000, c(25, 100))
aqp_df_class(res)
#> [1] "data.table"
```

**Comment by rolhar** [comment]
Thank you very much for looking into this, for solving the problem and for explaining the details as well as the internal function!
