### ISSUE TITLE
plotSPC - legend creation fails with NA

### ISSUE THREAD

**Issue by brownag** [ncss-tech/aqp#37]
when symbolizing on an attribute that contains one or fewer values (all others NA) plotSPC fails with  missing legend or missing values for the RGB color elements

can be reproduced by fetching a SPC from NASIS, setting all but one value in `horizons(spc)$clay` to  `NA` then trying to create a grouped profile plot with the thematic colors determined by clay (`color='clay'`)

```
f <- fetchNASIS()
f$clay[2:length(f$clay)] <- NA
groupedProfilePlot(f, groups='taxonname', color='clay') 
```

Case 1: all values of thematic var are NA
```
Error in legend("bottom", legend = color.legend.data$legend, col = color.legend.data$col,  : 
  'legend' is of length 0
```

Case 2: all but one value NA
```
Error in rgb(c.rgb[cc, ], maxColorValue = 255) : 
  argument "green" is missing, with no default
```

Case 3: two or more values non-NA
Works as expected.

**Comment by brownag** [comment]
OK, Fixed this with a `drop = FALSE` and an `if(length(...) > 0)`.

```
library(aqp)

data(sp1, package = 'aqp')
depths(sp1) <- id ~ top + bottom

# case 0: fine
plotSPC(sp1)

# case 1: fine (previously error with zero-length legend)
sp1$prop[1:nrow(sp1)] <- NA
plotSPC(sp1, color='clay')

# case 2: fine (previously error due to drop = TRUE)
sp1$prop[1] <- 17
plotSPC(sp1, color='prop')

# case 3: still works as expected
sp1$prop[2] <- 18
plotSPC(sp1, color='prop')

```

**Comment by brownag** [comment]
![image](https://user-images.githubusercontent.com/20842828/86652815-8f1a7a00-bf99-11ea-9ea8-2cd63e3187e2.png)

Note that the default legend in Case 3 above is pretty weird! Definitely an edge case

**Comment by dylanbeaudette** [comment]
Thanks. In attempting to make Case 3 (more common than you might think) result in a nice legend, I've opened #148.
