### ISSUE TITLE
shannonEntropy not exported in CRAN version of aqp

### ISSUE THREAD

**Issue by brownag** [ncss-tech/aqp#48]
When working with a version of aqp installed off CRAN, shannonEntropy not exported. Dylan, you're probably already aware that this isn't in the namespace. MUComparison report used to have a local definition of `shannonEntropy`, and it is now in `aqp`.
```
> aqp::shannonEntropy()
Error: 'shannonEntropy' is not an exported object from 'namespace:aqp'
```

Appears to be working correctly in the latest commit on GitHub.

**Comment by dylanbeaudette** [comment]
Yes, thanks for filing the bug. The CRAN version doesn't include the function. So, we should probably adjust  the related reports to install the github version of aqp for now. I'll try and push to CRAN this month.
