### ISSUE TITLE
aqp installation fail - dependencies

### ISSUE THREAD

**Issue by brownag** [ncss-tech/aqp#49]
I've noticed issues with `aqp` installation failing for both CRAN and devtools installs due to `stringi` package not being installed.

**Comment by dylanbeaudette** [comment]
Strange. `aqp` imports from `stringr` not `stringi`. Perhaps a dependency-of-a-dependency?

**Comment by pierreroudier** [comment]
Yes, `stringr` now depends on `stringi`.

@brownag Can you please try re-installing `stringr`: `install.packages('stringr')` ?

**Comment by brownag** [comment]
Well, I was reporting this because I was helping a co-worker with a problem they were having. 

It may have been because they installed most recent version of `aqp` with `dependencies=FALSE`,  and only had the `stringr` package?

```
> remove.packages("stringi", lib="~/R/win-library/3.4")
> remove.packages("stringr", lib="~/R/win-library/3.4")
> remove.packages("aqp", lib="~/R/win-library/3.4")
> install.packages("aqp")
Installing package into ‘C:/Users/andrew.g.brown/Documents/R/win-library/3.4’
(as ‘lib’ is unspecified)
also installing the dependencies ‘stringi’, ‘stringr’

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/stringi_1.1.6.zip'
Content type 'application/zip' length 14295451 bytes (13.6 MB)
downloaded 13.6 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/stringr_1.3.0.zip'
Content type 'application/zip' length 170712 bytes (166 KB)
downloaded 166 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/aqp_1.15.zip'
Content type 'application/zip' length 916302 bytes (894 KB)
downloaded 894 KB

package ‘stringi’ successfully unpacked and MD5 sums checked
package ‘stringr’ successfully unpacked and MD5 sums checked
package ‘aqp’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\andrew.g.brown\AppData\Local\Temp\1\RtmpEfTAoi\downloaded_packages
> 
```

**Comment by dylanbeaudette** [comment]
Hard to say: the more I work with this many folks / R / packages, the more I see strange cases like this. The solution: teach folks that `install.packages(xxx)` is generally the solution.
