### ISSUE TITLE
make a new plotting method for SPC objects

### ISSUE THREAD

**Issue by dylanbeaudette** [ncss-tech/aqp#59]
Something like this, optimized for smaller collections and eventually SoilWeb.

![image](https://user-images.githubusercontent.com/624277/46825110-a5a18c00-cd47-11e8-92ca-d27cf4078cf9.png)

**Comment by pierreroudier** [comment]
@dylanbeaudette what would be the meaning of "1", "2", ... on the x-axis?

**Comment by dylanbeaudette** [comment]
Great question. Those are some notes to me on how it might be implemented behind the scenes.  Kind like like this:

data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAwAAAAGACAMAAAAtcPVNAAABfVBMVEUAAAAAADoAAGYAAP8AOjoAOpAAOv8AZAAAZDoAZGYAZmYAZpAAZrYAZv8AgDoAgJAAm7Y6AAA6ADo6AGY6AP86OgA6Ojo6OpA6ZAA6ZrY6gAA6gDo6kNs6kP86tdtmAABmADpmAGZmAP9mOpBmOv9mZABmZgBmZjpmZmZmZrZmZv9mkNtmm2ZmtrZmtv9mz9tmz/+LAACLADqLAGaLOjqLOpCLZraQOgCQOmaQOv+QZmaQZpCQgACQkDqQkGaQtWaQtpCQz5CQ27aQ29uQ2/+Q5/+fAACfOgCfOjqfkLafkNuzAACzZmazttuztv+2ZgC2Zjq2Zma2Zv+2kGa2mwC225C22/+255C2/7a2/9u2///HOgDHkGbHtpDH27bH2//aZgDa/9va///bkDrbkGbbkP/btTrbtmbbz2bb29vb2//b55Db/7bb///tkDrttmbt/7bt/9vt///y8vL/tmb/tv//z2b/z5D/25D/27b/2///55D//7b//9v///8umYTFAAAACXBIWXMAAA7DAAAOwwHHb6hkAAAdcElEQVR4nO2djX8cN1rH1/E1y0FCk5JCCkl67JEe5cV0eyQ9QyhwNQESSFqTHuDcUYPPBo5mOcramGQ9f/vpkebNu5pZSTsjPSP9vp9rbr07j6SR9NNIGknPKAMgYUahEwBASCAAkDQQAEgaCAAkDQQAkgYCAEkDAYCkgQBA0kAAIGkgAJA0EABIGggAJA0EAJIGAgBJAwGApIEAQNJAACBpIACQNBAASBoIACQNBACSBgIASQMBgKSBAEDSQAAgaSAAkDQQAEgaCAAkDQQAkgYCAEkDAYCkgQBA0kAAIGkgAJA0EABIGggAJA0EAJIGAgBJAwGApIEAQNJAACBpIIC+uHj58Vf6Pxqu0XL+eDr9W3HVypUa0/WhgRUggL5YPP3+v+n/aLhGx8XL6fTjfxFXrVypMV0bGlgFAgjJfPqw/YLF07xRX3tlRk+LB990kaqkgAA6YzadTmUTPJv+/cvps9n0SZYdTqcPqe7SH+K/+XQq66j4Wn6Q18i+y08eyxquTIugFk/F/3/8VW6sYnhSxlYPka58Ur9mRl+fPzaQTeJAAF1BlVpWW1Gd/3r64H9ERZYVePo30ycXVKsPxSdVO9WlDzP5daaqr/xFmX5TBEUDgOn3/1VcdaH+m5YKuBxiHkDtGnp0iD+etCYZQACdIZriZ1QRZW18qDrkM9F8i1r68Vf0h6iO4q+Z+O38sfzw4Jui0z6fytr6MDetghLGz2RItdBUN+dyiLNp/ld1zYyeCGj/1wIBdIOsv1lev6laz6cPfi7r8FxUTvHHN6I5f6YukNCHeV6b5ZczeY18gpRBySEAXTWXj5SHKjQyuRSiauovX7N4+scYEhgAAXSDaLCpN3Mom2NVf5/Ilj4rhgCytqtOzzzvp+RDANnOSwHM1LOjDEoOa/PeftHNKTRTC1FFJIzr1xxOMSdkAATQDarWyn6LrM71elkMAZ5keXdG9ZOeFUMA+f+y3T/MAymCmucDhQs1oHhWRnc5RBXRoRRJcc2Mhs8hcmJgQADdIGqkaHap1VUzl2VNp36K6rCrxwF1Z0TTPJtWc/uy508df2VaBXVpCCAVono9xRCgCFF8+6QaSMhrxNf/jSGAARBAR8zzeZh8CECdl3xKhlroYsA7U5JQ3ZRi3j43LUYPVVCyitNV8sp5fhVxOcQyovIaeiaU7xBACxBAV1C9Lvr8+biWJmZ+nHfta0MA6p38eErTOqo2q+n8h9XbriIoKYhZOaygr5eH0CpE8Qz5+CdSTuqaeT7bikfAWiCA/jhUkztra+FhrXMPPAMB9Ifqj6zth2ANW0gggB6Zqa78GrCGLSQQAEgaCAAkDQQAkgYCAEkDAYCkgQBA0kAAIGkCCuD8sfULUKcljnO3dZEXL62n52cm771W4zF4V7DEYW1vmDnnjx0yQhhZ54MsWbVdhz3BBEDLV2zzZ06LjW2L4/zxQ4e6nJV7r8y5eOmyA+XwwTfW95S57IBfPH1on8Lzx08uXtotKVIlS1G53JdvQgmAFm05bVg6dGlWHEpiZt/CLp46bMGdu+3bddD0nLYQ2FrNaIullVFeshTbbACPgFACmD/4+VOXtYqLpw6yWdhHNZ/+nXXHZF4cC2FDcUCEdVzWuhGNuX1GUOW3E4AqWSlQp8bKM+HGAKI87I2cFo7N7WuYSJx96c1o5b9lDVM7x6xzwqlT5/BQo0Y836VgDt0PNVROifRNOAHMXBYBu60ctm4unbrLhLUVVRKnB5STZubW2Sf32lje00xuC3ro9rT2TTgBuIyQHFfOWzexh7Xt51ZY12VSjIMAHDoXlAlOT11rsVHJUkyOwxu/BBOASwvrctANlYTLYMx+ktYtJtFvsjdyaVtJZta6kVNo1g81uVPN8Rnqm2ACsO4tZ/lmWtt66Xg8goNonF44uLwGcG3JHZI3s38QqpIVhTWE+o83wSBtIACQNBAASBoIACQNBACSBgIASQMBgKSBAEDSQAAgaSAAkDQQAEgaCAAkDQQAkgYCAEkDAYCkgQBA0kAAIGnCCOD8nb1+LdTl9tG4xZazeH9n80AMmF85WPqGovq8Kbb51sovmmvXXKU+l7e0HGHxWRMKc6IWgGeWBNAbqwLI2qre6i+6a9uv0lhof4YAWjgaja5l2XP6V9RPUYqiwlx8Qn8u3h+N3nrVYCYu+dbNHarRwvSOKP0PRlcO1L/NcVEEW3syGrpQhaEiW03X1rujX/lEJEAlYz4aXfmSzN+lNMnkLqWyNKinSEWhrle3Wsaef3kJ9Useo4xKmwn1mMt7rpJWRH7+zmefjLb2luNR1nR5EZX8Rvyz9cMqNoOr6POneb5UEVL8z6+pEGTkdy6FspSvLTUjJP4EICqkqPGy3t8pBSA+/P+P8l8b7I5EdksBHEkLqtc383+bIzt/54ff2StkcHOnDENFthTB1t58tKOCm8vPuaFIaJnceipLg3qKVBTqenWrZezqy5XcqGKUUWkzoR5z3URcX49cRbUSj7IWaVXPJtUk0DcyniI2k6su5UsZ4dFbX6uHHn1WyamFspSvzYUVFH8COFKtJzVd10oBUDOmmshmAVATQjkuLhKNjLLLrRs5f+fdrb3qQaPCyCNbiUA8UFTdksmYl4YioSq5S6ksDeopUlGo69Wt1mNXLWWN6va38qj0mVCLubxndX098qI+LscjrZUc8+CLb+qxrbvqaPTWv9fzpYxw8Z2/+DWZn/OtonRqoSzla3NhBcVSAMfb29s7x3ddYhKZcfFJ1aSW7ZnIsOfUDVj/BJDVylQAeyLQqgrKMDJ9N72qzzIZRUFTW3anbFTrqSwN6ilaegKIWy1j1z4B5C95jDKqpkyoLisFIK+vR97wBFDWqlKWwatvLse29qq5VgDZ81+/VpRtnpxaKEv52lxYQbETANX/7Z39bafB3tGo7FSL/BMdw7xbLrvd32rs0IhLflnmeH6tqQDqVVCFoQJYTVdRUCoZZUF/cGkMUEtlaVBP0fIYoCY//RhA9RhkjDIqbSbUY64EIMcA9chFVOc39WMAWfnKqNQ34tpPq9hMrqLPSwKgCKlblKmfP1sJZSlfmwsrKHYC2N0+eH1r5/Wtq36HNF1Mr9iGoZ1q6QePUXXMcFNeYieAyfVMCCDb3/Z43+c3N59DcAgDAljP0ejO+ouYY/kEuPrKuwAA6BHrMcCPAnSBAOgLy1mg3W0J1yE9AJbYvgc4bar/u5AFGCDWg+AGxOgAIwMwPGwEMNneVgLYXanqp9s7YoBQPQK2SzZPIgB6Fu+PNp4ft3oCqBHAdY0A6Jt9rQCWFDDSsi6RMIrXyBRNiEc7i+++kjL46fe2PnWbk7XsAuWVemUWaCK+WZVFRkpYiu9/NazNWBjFa2SKJpwvDuh/Rzvn7x3dmV9bfNhRsC3IMYB4DiwvBnp967oSwQopC6B1U0L45LnfU1NVCyMA8b/sp3vzOz4E0MTrW3fFMEC3Ri5lARz9bstDOXzynO/p/KZmV4VzTKZowlFdIPr3H3wJgPpAurme3es0D6T5wVQAzFtLl+Rd/OCfvtv8wnDI92T7BOhkf57mNtUgWI4BPAlgvxjZLovg9a3VcYHEVADMW0uX5M3FcK15kmLI92QrgNaYTOlp54rlGIBm+3UCaMRQAB5bS2+N+fOdbN7QV+j6nlyMNrgnSwG0x2QKDwFcz45pPZz5jhhDAXhsLX015ue/IfoKv93YUgQXwAb3ZCmA9phMYSEA0c8/pRl/88VwhgLw11r20Zg7zZl3eE9ORv7uqT0mU1gI4Hj7LjX/2hl/PWYC8NhaxtiYuxj5u6c1MZnCQgDZ/l05EdT5E2BNIjs0Yt4z5z4d1r2RKTwEkMkJH4tVb9wEwL4xZz4dRvqk3cDdxWQKGwHY0c1aIH/lHjp5fUyHdXlPpM/P9xqeoU4xmcJCANT6ry6EaIPbE4C7kdt0mLd+U67PuT6J8T8BdptehDUCAdgZuQ1RvPWb3F6EdQILAaj1bhMuAohvwOg2RPH3GlHqszGB8Qtgt3FHWBO9CqC94Qvdnfdn5O01otLnB9ozhl1jMoWFAE6tdz32KQDmq82O5AGZTR2G8P0mJhlhCgsBZPu2j4A+BcB8tZko8vkfvn/lS/3i4eD9Ji4ZYQoLAUzUlkgLbJZDFy3FaiL1RvwbvtGOlydAH0YddiDbM8IUPgLoZRaIuvN5S7Ea9mAbvvP3BisAbxlhCgsBSE77Wg5dtBSriQxdhE5GVO6/DwGsywhTwgtAu+d3HTbLoYuWYjWRoYvQyehIepm40rB4OHjy/Bm1Z4QpLAQwsT4Y0WY5dNFSrCYydBH2YZTOLG03hBdA1t8YQHXn/yxvKVYTybsIYbSJkSksBCCxWg6KpRAw6gY+ArACAoBRN4QXwMTuDYACAkjJKO7l0MUAwMpHJAQAo24IL4DcOQCWQ8OoSyNTOAggO96Wh+BCADDqzMgUFgLIHWRMNjgXKPT0t9MazTVG/u4pdO5Va7Y6i8kUHgJQL4MtfMGwewI4rdH0trCTvVGxZku7Cjd+AezLzs/rW0MWgMsazWEv7OzQqFqz1VlMprAQQDETZD4fyk8ALms0sbAzN6rWbHUWkyksBLC7d2q5I6AbAXS5ON1ljSYWduZG1ZqtzmIyhYUAJrq+D/mOb3STyu8J4LJGEws7lVFtzVZnMZnCQgD7mko+kTW/yU0qOwHAiJmRKbpwRIO0qadIy+TtLiuAVsZdfdXiJhUCgFEnaMIhX02beoq07QIt7wc4vfqKXg6Yu0nlXRow8m5kim70J54Am3qKdBHA5TfB0l0G3KTCKEwXaFNPkQ7JW9oTfCx6P3CTCiNXI1MaBLCpp8jNk0djX7hJhVGzUb6QpPFUdTNaB8HuniItBSCPh758G9I96sZuUtsTCaMhG+ULSb7XdKq6GSymQU9XXwTL3s/mblLbEwmjIRuVx900nKpuBgsB7Ir+PqnA/EYgABhFdDCWWg79+taAfYTByMyo+9UnGzrKYySA7r1ErkskjIZslC8kaTxV3QwWAshfBEMAvRk1HhDMI3k9GJnCQgDH22oQgC5QX0aNBwTzSF4PRqawEADtiCEGMQgOvn3QxajxgGAeyevByBQeAlAToRbvM/AEsDNqPCCYR/J6MDKFiQBsgQDsjBoPCG41GvLAwRQeAtC8CW4HArAzOmo6ILjVaMgDB1NYCEDzJngNQxMABg6+jUxhIQC8CWZpNOiBgyksBIA3wSyNnAYOXO7JFEYCwIswZkZOAwcu92QKCwHgTTCMujYyhYUA8CYYRl0bmcJCAIN6EwyjQRiZwkMAeBMMo46NTGEiAFsggJSMXN6imMJDAPu2zrIhgISMeoWFANTx6LvoAsHIOywEoA7HnWAQnKpRu6ucXuEhAPkiDNOgyRq1u8qpGI/XhG8PCwHkb8DwIixVo3ZXORWxCkC9CNO7CdADAURlZHrCSawCKF6EbeAlMnQRwmgTo3ZXOb3CQwBqR4yFr3gIICqjdlc5vcJEALYYCsDJe287wY3az4QNnrwejHqFiwBOLdzEZ+YCiNARb/uZsMGT14NRr0QugAgd8bafCRs8eT0Y9QpXARzni+M28xIZoyPeGO/JlGhngVYEQG4xyEXGhl4iY3TE234mbPDk9WBU4UcANLzy6yVyol0FtL+9t6mXyBgd8bafCRs8eT0YVfgRwOd75LXbs5dIjQQmV1/BS6S1kdMBLLxPbekV7Q3Pd/x6iZRuIpef6LRRGF4iWVWWS0RyT7rIQ3iJXJHAPrxEsqssl4jknjSR0/DKv5dI+S64kgDV/0BeIpM4EnNz/OVer2gify6GV569RBLH9dMRj9WnIF4ikzgSc3P85V6vsJgGnVRjW9Xcy8eB7AMF8BIZyZGYTjMmFkb+cs8peaawEYCs+cbvg3t+AsRwJGYoAXSfe07JM4WFACpM98T0LYAIjsQMKICOc88peaZwE4Dhrsieu0DxH4m5Of5yr1eYCcAUTIMGJ5J7ggDiMvJHJPcEAcRl5A9/KzV6BQKIy8gfkdwTDwHol4O2EIcAetjdWBFoFqgHI6fkmcJCAPty1XPMTvIaBND97sYKCMAIFgKYXH1leSxEJALofndjBQRgBA8B3JWLf5I7Ga6H3Y3+wBigu2B3r8uTcbWbH/XEI4COdzf6AwLoLli5EPRAv/JfTyQC6H53oz8ggA6D3ac9kbvJjQF6MPJHJPfEQwCS/eRmgXow8kck98RIADZAAGvBLJARPASg2xTfCgSwFgjACBYC2C/2gw13FojLkbUVEIARLAQwofPfBi4AJkfW+iOSe+IhgOvZMb0MHvAsEJcja/0RyT2xEMDu1VendAbcgN8DcDmy1h+R3BMLARxv36Xmf8hLIbgcWeuPSO6JhQCy/btyImjITwAmR9b6I5J74iGATB0FZD4Tyk4AXIwqMAtkBAsB/I5xy18AAawFAjCChQAmNnthJBDAWiAAI1gIgLo/Fj5SMwiAAZHcEwsByDMRt21c0kAAwYnknpgIoPKKZwYEEJxI7omNAKRDyGoa6LQTL5FrEhmhkT8iuScWAiiOR6/eA5BvmN3NvUSuSWSERv6I5J64CEBTyUXN39RL5JpERmhUgVkgIzSRz0e+3aTqmaiHgJmXSN5+Dt2MSsZjh2MEIQAjNNXlP7P5jl83qTpOqUOUtJfIir7rspPRYDJiTYo0382vHPh1k6o8Ii29CTilFXIpe4lkTiQZoY38/D2/blJ3dTvCXt+6G8ZLJBcj5kSSEZrIP99bfOjXTapq5GtDYar5NPgN4iWSixFzOl5L27KhtFc0KaZk+HWTuruyFCh/LRbESyQXI+Z0vJuiZUNpr7CYBj21OxIigwAY0PEToGVDaa+wEIDVmViStAQQ/SxQ+4ZSp+SZwkIAk7qTeCMggOBG/jaUOiXPFD4CGPaxKD0YVcQvgNYNpU7JM4WFACSnEMCgiCQj+AjACgggOJFkBA8B4GzQ4RFJRrAQQARng/ZgxJxIMoKFACI4G7QHI+ZEkhE8BBDobFCX9cYbxuTkID36WaAekmcKCwEEOhu0IsZyhwCMYCGAQGeDVsRY7hCAESwEEOhsUCci6fpuTiQZwUMAWZCzQZ2IpNw3J5KMYCMAOyCA4ESSETwEYDH8VRgKoIeNFpGU++ZEkhEsBLAvez+7FpXUVADdb7SIpNw3J5KMYCGAiez9TyxOBzV/AhhttIhx8gOzQEbwEIDcC3Da/SxQDxstBlPuEIARLASQvwDo/j1ADxstBlPuEIARLARwrM5Gn3QvAMONFhZE0vXdnEgygoUAiuWgntcCORFJuW9OJBnBQwDqbDgLJzEQQHAiyQgmArAFAghOJBkBAVgSSblvTiQZAQEQMU5+YBbICAiAiLHcIQAjIAAixnKHAIyAACyJpOu7OZFkBGMByBfDfXqJdCKSct+cSDKCrwD2aWlQr14inYik3DcnkoxgK4BjejHWr5dIJyIp982JJCN0kV/84CC4l8jT7d8Tld/cS6Q/AXjzR8kct4zY7HyYHtAlY37lILSXyNe37lLF79dLZAXLGRN/yYvbqB1NKVz86Z949hK5ykQ6B+vZS2QFBBCxUTuaUpjvfHHg10vkCmp16NWf9eslsgICiNioHU0pHI1G1/x6idTx+tZO1rOXSH+079mfj/w7RwQ52kryxYFfL5E6jvv3EumP9j37nwXwDQdy2E6DthOJAPI9+/Mrtl4yQVdAAD5Ys2df/Bs6hckSiwDYzS9fon3P/ud79n1M0BGRCKCC5ZRE+579L9cdXMfyngZj1A4E4MMI06ABjdqBAHwYQQABjdqJTgAsYT5GTxkIwAcQAFsgAB9AAGyBAHwAAbAFAvABBMCW6ATAckoCs0ABjdqBAHwYQQABjdqBAHwYQQABjdqJTgAswRiALRCADyAAtkAAPoAA2AIB+AACYAsE4AMIgC3RCYDllARmgQIatQMB+DCCAAIatQMB+DCCAAIatROdAFiCMQBbIAAfQABsgQB8AAGwBQLwAQTAFgjABxAAW6ITAMspCcwCBTRqBwLwYQQBBDRqBwLwYbThyY0s72kwRu1wFcAxecjYM3aTCoAbXAWQ+8UwdZMKgBuamnp+c7QT3EvkRDpGMnaTCoAbWh9hWRbaS+Qp1fEDczepALihGZMdjbb2QnuJPN4+IBeRjW5SAeiRxYeBvURKdq/+rNFNKgC9QQ5LwnuJJF/BrxvdpALQG+c3t/YCe4mkmk+D30Y3qQCwpotBcJubVABYg4VeIGkgAJA0EABImpACGIN4CVivrAgngNAlBHolWL2yJKQAYASj4EAAMOJiFAQIAEZcjIIAAcCIi1EQIAAYcTEKAgQAIy5GQYAAYMTFKAgQAIy4GAUBAoARF6MgYC0QSBoIACQNBACSBgIASQMBgKSBAEDSQAAgaSAAkDQQAEgaCAAkDQQAkgYCAEkDAYCkgQBA0kAAIGkgAJA0AQXw5vZHtiYn4/Ev/ZWt0ZmLUZZdPPq2rcsnkTz7qC4ejce2GfFCHr52z9LqzW2HjBBG1vkgS1bcl0u2+yaYABb37fPnTJT5C9vieHP7hkNdpkr2tqXHg4tHthYynrdfWd9TRrdlG9ni/g37FL65fe/i0Q3LeKhkKSqX+/JNKAGIhsW6gkleuDQrDiVxYt/CLu7bWmRK1A44aPpMPGisM+JEZLedUV6yFNvJAB4BoQRw9vbX9+0aFsXivoNsFvZRnY3/wLpjIvpa9t0F6s043JKDbkRjbp8RVPntBKBKVgrUqbHyTLgxgCgPe6OLRw55emZfw0Ti7Evv5NsHor9lZyN6yh855IRTp87hoUaN+JvblnHR/VBD5ZRI34QTwIl1C5tRe+lgZN9cOnWXCWsrqiROD6h7tiYU05l19tEQ3bb9oJKllsDpae2bcAJwGSG51X/7h42aZfHR2SLFOAjAoXNBmeD01LUWG5UsxeQ4vPFLMAG4tLAnY/thA5WEy2DMfpLWLSbRb7I3cmlbSWbWupFTaNYPNWFw8cjxGeqbYAKw7i2r+QX7OXOndweZi2icXji4vAZwbckdkndi/yBUJSsKawj1H2+CQdpAACBpIACQNBAASBoIACQNBACSBgIASQMBDBRaFeW0MgpcAgIYKIv7tIioYTnJ/0EXpkAAA6VtQ8zZIN7B8gAC6Apa0yAb5GKF/8n43hl9ohXPGf0pvix+k4ss87Ug8oc3t4s/y3BOyu0F5aeT8R+JwBb3x+N7IvQs/+8sX66gAi/Wb544bJpMEAigI6hWjos6Liv3i/FvqZ27L6givrlNe6vy39TFeZVf3KfefFFZl8Khel9+En3+3xy//bUyHn8klVXGUgQuA7ghZQAFrAcC6AjaQkyVXFb0E9USy0831CJWUkH525lqovMe/Am15zeWwjmjNXKiMtOq4uKT+OdGJu1k4DQEqGKpRSw/SL2hL7QOCKAbRN2srelUFZK+oU9nsk4X49X8t1rdXNz/1bJDX4QjKvYNdXH1KZOBqIfFWS6jKpYy8FwXN+iiAWzJCgwE0A2y/ZWc5X0P2crLXoqokf+sxgHFb7KDXknghayockvxP+bh5EJ4Ibs0+SdVz1VM6slSj6UWcdnHwhNgLRBANxQtfNFV+Uj1/OVEpeiT/DlVxeo3dWHxzMh3LJAo3v6vKpyPVGjVJ7UhTglAhJ4PAe4VU6JF4Ce1WMA6IIBuoGpJdVD2OlQvneqp2o//Qu3jKX97UTXbmbzmP8ohQBGO+FUOhGVvJv9Eo2W504Ra+WIIUMRSi1iEK7tAqnsEWoEAOuKF6nGoXWtj2uhLTfmJnIc5URM+5W/5B9XWqypfvtLNw8k7NFXXRm40J4t8fodOoKjHUot4LMcd1TQTaAEC6Aiql2r2fyw6PHQAQ9XKn+V7EYvfVBdd9c/P8inMG0vhyBqtzIpPZ+oiOnntL0XlL8bXeSxl4Or0EzJC/V8PBACSBgIASQMBgKSBAEDSQAAgaSAAkDQQAEgaCAAkDQQAkgYCAEkDAYCkgQBA0kAAIGkgAJA0EABIGggAJA0EAJIGAgBJAwGApIEAQNJAACBpIACQNBAASJpfAOYkfCDSXLheAAAAAElFTkSuQmCC

**Comment by dylanbeaudette** [comment]
Note that `aqp::explainPlotSPC` now exists for creating these diagnostic plots. There is still work to do on the various "fudge factors" employed by `aqp::plotSPC`: #62.

**Comment by dylanbeaudette** [comment]
Note to self: consider options for SVG vs. PNG output. It can be 10x larger though...

```r

library(soilDB)
library(sharpshootR)

x <- fetchOSD(c('amador', 'pentz', 'auburn', 'hornitos'))

svg(filename = 'profile-test.svg', width = 6, height = 4, pointsize = 10, family = 'sans')
par(mar=c(0,1,1,1))
SoilTaxonomyDendrogram(x, width=0.2, scaling.factor = 0.04, cex.taxon.labels=0.75)
dev.off()

png(filename = 'profile-test.png', width = 600, height = 400)
par(mar=c(0,1,1,1))
SoilTaxonomyDendrogram(x, width=0.2, scaling.factor = 0.04, cex.taxon.labels=0.75)
dev.off()
```

**Comment by dylanbeaudette** [comment]
Another good reason to switch from PHP/GD to R, neutral hues:

https://casoilresource.lawr.ucdavis.edu/sde/?series=webster

**Comment by dylanbeaudette** [comment]
See recent post by Murray Lark, with a great idea for "soil cards". https://twitter.com/DylanBeaudette/status/1141401414788239360

**Comment by dylanbeaudette** [comment]
UPDATE 2020-06-24. 

The following demonstrates some new functionality.

```r
library(aqp)
library(soilDB)
library(sharpshootR)

## TODO: get this list via line -> densified points -> SDA query -> component names
s <- c('exeter', 'san joaquin', 'tachi', 'tranquillity', 'Calflax', 'zook', 'palau', 'pierre')

x <- fetchOSD(s)

x$hzdo <- runif(nrow(x), min=0.5, max=10)
x$hzdo.const <- rep(10, times=nrow(x))

par(mar=c(0, 0, 0, 3))
plotSPC(x, width=0.25, cex.names=0.85, shrink=TRUE)
plotSPC(x, width=0.33, cex.names=0.85, shrink=TRUE, name.style='left-top')
plotSPC(x, width=0.33, cex.names=0.85, shrink=TRUE, name.style='left-center')
plotSPC(x, width=0.33, cex.names=0.85, shrink=TRUE, name.style='left-center', hz.depths = TRUE)

par(mar=c(0, 0, 0, 0))
plotSPC(x, width=0.33, cex.names=0.85, shrink=TRUE, name.style='left-center', plot.depth.axis=FALSE, hz.depths = TRUE)
plotSPC(x, width=0.33, cex.names=0.85, shrink=TRUE, name.style='left-center', plot.depth.axis=FALSE, hz.depths = TRUE, hz.distinctness.offset='hzdo')

## TODO: finish truncation of offsets
plotSPC(x, width=0.33, cex.names=0.85, shrink=TRUE, name.style='right-center', plot.depth.axis=FALSE, hz.depths = TRUE, hz.distinctness.offset='hzdo.const')

plotSPC(x, width=0.33, cex.names=0.85, shrink=TRUE, name.style='left-center', plot.depth.axis=FALSE, hz.distinctness.offset='hzdo', divide.hz=FALSE)


par(mar=c(0, 0, 3, 3))
plotSPC(x, width=0.33, cex.names=0.85, shrink=TRUE, name.style='left-center', color='texture_class')
plotSPC(x, width=0.33, cex.names=0.85, shrink=TRUE, name.style='left-center', color='texture_class', col.palette.bias = 0.5)

plotSPC(x, width=0.33, cex.names=0.85, shrink=TRUE, name.style='left-center', color='bottom')
plotSPC(x, width=0.33, cex.names=0.85, shrink=TRUE, name.style='left-center', color='bottom', col.palette.bias = 2)

SoilTaxonomyDendrogram(x, width=0.25, shrink=TRUE)
SoilTaxonomyDendrogram(x, width=0.33, cex.names=0.85, shrink=TRUE, name.style='left-top')
SoilTaxonomyDendrogram(x, width=0.33, cex.names=0.85, shrink=TRUE, name.style='left-center')





x <- fetchOSD('scatlake')
y <- fetchKSSL('holland')

par(mar=c(0,0,0,0))

plotSPC(x, print.id = FALSE, plot.depth.axis = FALSE, cex.names = 1, scaling.factor = 1.2)
plotSPC(x, print.id = FALSE, plot.depth.axis = FALSE, cex.names = 1, scaling.factor = 1.2, name.style = 'left-top')
plotSPC(x, print.id = FALSE, plot.depth.axis = FALSE, cex.names = 1, scaling.factor = 1.2, name.style = 'left-center')
plotSPC(x, print.id = FALSE, plot.depth.axis = FALSE, cex.names = 1, scaling.factor = 1.2, name.style = 'left-centerd')

plotSPC(y, print.id = FALSE, plot.depth.axis = FALSE, width=0.3, shrink = FALSE)
plotSPC(y, print.id = FALSE, plot.depth.axis = FALSE, width=0.3, shrink = FALSE, name.style = 'left-top')
plotSPC(y, print.id = FALSE, plot.depth.axis = FALSE, width=0.3, shrink = FALSE, name.style = 'left-center')


plotSPC(y, print.id = FALSE, plot.depth.axis = FALSE, width=0.3, shrink = FALSE, color='clay')
plotSPC(y, print.id = FALSE, plot.depth.axis = FALSE, width=0.3, shrink = FALSE, color='clay', name.style = 'left-top')
plotSPC(y, print.id = FALSE, plot.depth.axis = FALSE, width=0.3, shrink = FALSE, color='clay', name.style = 'left-center')


data(sp1)
# convert colors from Munsell to hex-encoded RGB
sp1$soil_color <- with(sp1, munsell2rgb(hue, value, chroma))

# promote to SoilProfileCollection
depths(sp1) <- id ~ top + bottom

plotSPC(sp1, name.style='right-center')
plotSPC(sp1, name.style='left-top')
plotSPC(sp1, name.style='left-center')


# encode
sp1$hdo <- hzDistinctnessCodeToOffset(sp1$bound_distinct)
sp1$ht <- hzTopographyCodeToLineType(sp1$bound_topography)

par(mar=c(0,0,0,0))
plotSPC(sp1, width=0.33, cex.names=0.7, shrink=TRUE, name.style='left-center', plot.depth.axis=FALSE, hz.distinctness.offset='hdo')

plotSPC(sp1, width=0.33, cex.names=0.7, shrink=TRUE, name.style='left-center', plot.depth.axis=FALSE, hz.distinctness.offset='hdo')

plotSPC(sp1, width=0.33, cex.names=0.7, shrink=TRUE, name.style='left-center', plot.depth.axis=FALSE, hz.distinctness.offset='hdo', lwd=2)

plotSPC(sp1, width=0.33, cex.names=0.7, shrink=TRUE, name.style='left-center', plot.depth.axis=FALSE, hz.distinctness.offset='hdo', lwd=2)


plotSPC(sp1, width=0.33, cex.names=0.7, shrink=TRUE)
plotSPC(sp1, width=0.33, cex.names=0.7, shrink=TRUE, hz.distinctness.offset='hdo')
plotSPC(sp1, width=0.33, cex.names=0.7, shrink=TRUE, hz.distinctness.offset='hdo', hz.topography.lty='ht')
```

**Comment by dylanbeaudette** [comment]
Started the processing of re-writing `plotSPC` using grid graphics, will name the function `sketch`.

**Comment by dylanbeaudette** [comment]
The original idea is best implemented in `sharpshootR`.
