### ISSUE TITLE
test_hz_logic overhaul

### ISSUE THREAD

**Issue by dylanbeaudette** [ncss-tech/aqp#65]
This function needs a total re-write. It is an important component in `soilDB::fetchNASIS()`.

   * this checking assumes that the data are sorted!
   * give a reason for failing
   * perform checks and then report matrix of pass/failure

**Comment by brownag** [comment]
You addressed this issue a while back. `test_hz_logic` is deprecated and replaced with of `hzDepthTests` and `checkHzDepthLogic`. Recently, `spc_in_sync` (may be re-named) was added to determine collection level validity in a similar format to the horizon functions.
