### ISSUE TITLE
cleanup of profile_compare()

### ISSUE THREAD

**Issue by dylanbeaudette** [ncss-tech/aqp#7]
Bugs:
- `profile_compare` expects input data to be sorted by ID/top before use, this is not always the case after editing IDs via `profile_id(SPC) <- new_IDs`
- `tapply`, `split`, and functions that call these two will implicitly re-order data via conversion to factor
- `unroll` should be replaced with `slice`
- IDs ordering likely a problem anytime `union` is used to combine data
- character vars not converted to factors, causes error

Misc:
- user-defined slices
- sensitivity analysis
- S4-cleanup, this would solve several issues related to ordering
- consider using 'ff' package for file-based storage of VERY large objects. Probably just the dissimilarity matrix
- slice() would allow for a more nuanced definition of which depths to include
- we are suppressing warnings from daisy() when input is all NA, this is fine for now, but we should figure out a better way
- allow for other distance-computing functions
- allow for 'weights' argument (when metric = 'Gower') to daisy()
- determine practical significance of 'filter' argument
### site/hz properties combined
- 2012-02-28: partially implemented, but no way to control weighting

>  D = (D_hz/max(D_hz) \* w_hz) + (D_site/max(D_site) \* w_site) / (w_hz + w_site)

**Comment by dylanbeaudette** [comment]
More ideas [on large distance matrix storage](http://kbroman.org/blog/2017/04/30/sqlite-feather-and-fst/).

**Comment by dylanbeaudette** [comment]
Consider replacing NA distance (within soil profile) with 0: e.g. "no data, profiles cannot be distinguished".

**Comment by dylanbeaudette** [comment]
Finish documentation:
  * http://ncss-tech.github.io/AQP/aqp/profile-compare-factors.html
  * http://ncss-tech.github.io/AQP/aqp/aqp-profile-dissimilarity.html

**Comment by dylanbeaudette** [comment]
New package: https://cran.r-project.org/web/packages/gower/vignettes/intro.html

**Comment by dylanbeaudette** [comment]
New issues related to editing the profile IDs after SPC init, the resulting distance matrix is corrupt (labels don't match entries) because of implicit sorting by `split`.

```r
library(aqp)
library(cluster)
library(ape)
library(sharpshootR)


data(sp4)
depths(sp4) <- id ~ top + bottom

# make copies
x <- sp4
y <- sp4

# edit IDs after SPC init
# !! no sorting performed
profile_id(y) <- sprintf("%s-zzz", profile_id(y))

## labels are fine
par(mar=c(4,1,4,1), mfrow=c(2,1))
plot(x, color='clay', id.style='side')
plot(y, color='clay', id.style='side')


## compare: depth plots are correct
x.d <- profile_compare(x, vars=c('ex_Ca_to_Mg', 'CEC_7'), k=0, max_d=40, plot.depth.matrix=TRUE)
y.d <- profile_compare(y, vars=c('ex_Ca_to_Mg', 'CEC_7'), k=0, max_d=40, plot.depth.matrix=TRUE)

## labels are adjusted, as if sort()-ed
cbind(
  x=attributes(x.d)$Labels,
  y=attributes(y.d)$Labels,
  sort=sort(profile_id(y))
)

## distance matrices are different
as.matrix(x.d) - as.matrix(y.d)

# cluster
x.diana <- diana(x.d)
y.diana <- diana(y.d)

par(mar=c(1,1,5,1))
plotProfileDendrogram(x, x.diana, scaling.factor = 0.8, y.offset = 10, color='ex_Ca_to_Mg')

# doesn't work due to sorting bug
plotProfileDendrogram(y, y.diana, scaling.factor = 0.8, y.offset = 10, color='ex_Ca_to_Mg')
```

**Comment by dylanbeaudette** [comment]
Added a new fail-safe until there is a fix. This example demonstrates the error.

```r
library(aqp)

data(sp4)
depths(sp4) <- id ~ top + bottom
  
# edit IDs after SPC init
# !! SPC records are not re-sorted
profile_id(sp4) <- sprintf("%s-zzz", profile_id(sp4))
  
# fail-safe triggered
# expect an error until #7 is resolved
d <- profile_compare(sp4, vars=c('ex_Ca_to_Mg', 'CEC_7'), k=0, max_d=40)
```

**Comment by dylanbeaudette** [comment]
Jon makes an important point: Gower's distance should be constrained to a known range of {0,1} not matter which characteristics are included, how they are weighted, and the types (ratio, ordinal, nominal, binary). The distribution of distances is affected by mixtures of characteristic type, but does this matter?


```r
library(cluster)

# ratio scale data, with various scales
x.1 <- data.frame(1:10, 20:1)
x.2 <- data.frame(1:10, runif(10))
x.3 <- data.frame(rnorm(10), rnorm(10) * 100, 5, 1:10)

# mixtures of ratio, nominal, orginal
y.1 <- data.frame(1:10, 20:1, factor(letters[1:4]))
y.2 <- data.frame(1:10, 20:1, factor(letters[1:4]), factor(letters[5:8], ordered = TRUE))
y.3 <- data.frame(factor(sample(letters[1:4], size = 10, replace=TRUE)), factor(sample(letters[5:8], size=10, replace=TRUE), ordered = TRUE))

# combine resulting distance matrices for comparison
d <- list(
  daisy(x.1, metric = 'gower'),
  daisy(x.2, metric = 'gower'),
  daisy(x.3, metric = 'gower'),
  daisy(y.1, metric = 'gower'),
  daisy(y.2, metric = 'gower'),
  daisy(y.3, metric = 'gower')
)

# keep track of characteristic types
names(d) <- sapply(lapply(d, attr, 'Types'), paste, collapse=' ')

# inspect distributions of distances
par(mar=c(4.5,4.5,1,1))
boxplot(d, horizontal=TRUE, las=1, ylim=c(0,1), xlab='Gower Distance')
```
![image](https://user-images.githubusercontent.com/624277/64899461-50998480-d640-11e9-9dab-83bd2e209544.png)

**Comment by dylanbeaudette** [comment]
A new name for `profile_compare`: Numerical Comparison of Soil Profiles, or *NCSP* for short.

**Comment by brownag** [comment]
I am bumping up against this issue in aqpdf. Basically, an example is broken for profile_compare because of the ability to retain original order of an spc with numeric IDs. 

70706963ce38aeda11bb115de24895e466a96367

I think this ultimately comes back to the use of `tapply` within `pc` and not doing any reordering. I think I could probably "fix" this -- but it is buried way down deep in profile_compare and I am really not comfortable modifying it. 

I commented out the example for now. The IDs in the "depth matrix" plot are in the "correct" order -- but I am thinking the profiles could be out of order. I will post images in next comment.

**Comment by brownag** [comment]
These images show that the ordering of ID in the matrix plot is "correct," but the profiles are out of order.

![image](https://user-images.githubusercontent.com/20842828/85160737-97da2480-b213-11ea-970b-c0e3d6b6b265.png)

![image](https://user-images.githubusercontent.com/20842828/85160763-9f013280-b213-11ea-8c0f-7a316ed496ee.png)

**Comment by dylanbeaudette** [comment]
Fixed long-standing bug in the use of site-level attributes, there is no reason to enforce `n > 1`. Need to do the same for horizon-level attributes.

**Comment by dylanbeaudette** [comment]
See `/misc/test_suite/check_profile_compare.R` for a simple test based on the latest `plotProfileDendrogram`.
![image](https://user-images.githubusercontent.com/624277/85181049-de427a00-b239-11ea-993b-9d5fc44bc176.png)

**Comment by dylanbeaudette** [comment]
`profile_compare` is being retired, as the newly re-written `NCSP` is almost done.
