### ISSUE TITLE
store `slice` ,`slab`, and related results in original SPC

### ISSUE THREAD

**Issue by dylanbeaudette** [ncss-tech/aqp#73]
The new `SoilProfile` object will be more flexible than the existing `SoilProfilecollection` objects. Extending @horizons to a list would make it possible to store several levels of support:
   * `original`
   * `sliced`
   * `slabbed`
   * `something else entirely`

Accessing the horizon-level attributes would extract from `original` by default but could just as easily extract for any available level.

It could be done in pieces:
```r
# ?
append(x) <- resample(x, ...)
# ?
append(x) <- changeSupport(x, ...)
# ?
append(x) <- reBase(x, ...)
```

Or all at once by slicing/aggregating according to some reasonable defaults. Suggestions on the function name welcome.
```r
# modify in place or replace by assignment?
x <- kaPow(x)
```

![image](https://user-images.githubusercontent.com/624277/50458116-962cea80-0915-11e9-869f-54dbeac1aa49.png)

**Comment by dylanbeaudette** [comment]
Closing as too complicated, not well defined.

**Comment by brownag** [comment]
I was a proponent of this at one time, but I don't think it is needed, and we should probably not introduce this complexity into the horizons slot. It is fine to just have this kind of information in separate SPCs.
