### ISSUE TITLE
reduce dependencies (if possible)

### ISSUE THREAD

**Issue by dylanbeaudette** [ncss-tech/aqp#79]
Relevant commentary:
   * http://dirk.eddelbuettel.com/blog/2018/02/28/#017_dependencies
   * http://www.tinyverse.org/ 

Some ideas on replacements:

   * `plyr` &rarr; `purrr` / `furrr`
   * `reshape` &rarr; `reshape2` (no longer maintained)
   * `stringr` &rarr; `stringi` (fewer dependencies)

Dropping `plyr` entirely is going to be very hard; `plyr::join` is used extensively.

Another approach, suggested by @smroecker: `plyr`, `reshape` &rarr; `data.table`

I am leaning towards the following:
   * `plyr::join` &rarr; `merge(..., sort=FALSE, incomparibles = NA)` (base) or equivalent from `data.table`
   * `plyr::ddply`  &rarr; `split` / `lapply` (I'll miss the syntactical sugar and NA-handling)
   * `melt` and `cast` / `dcast`  &rarr; [`data.table::dcast`](https://r-posts.com/benchmarking-cast-in-r-from-long-data-frame-to-wide-matrix/)
   * `plyr::rbind.fill` &rarr; `data.table::rbind.data.table(..., fill=TRUE)` 

**Update 2020-06-16**: `data.table` seems like the solution to most of our problems, and, gives us automatic parallel processing.

**Update 2021-01-20**: see #157 for `data.table`-specific changes and replacement of `reshape` + `plyr` functionality.

**Comment by pierreroudier** [comment]
reshape → tidyr ?

**Comment by dylanbeaudette** [comment]
Blurg... Haha, must resist hipsterverse.

**Comment by dylanbeaudette** [comment]
Some ideas from [itdepends](https://speakerdeck.com/jimhester/it-depends)/

Still not my preferred syntax, but this felt rather natural:
```r
dep_usage_pkg('aqp') %>% 
count(pkg, sort=TRUE) %>% 
as.data.frame %>% 
knitr::kable(., row.names = FALSE)
```

```
|pkg          |    n|
|:------------|----:|
|base         | 5322|
|aqp          |  203|
|graphics     |  104|
|stats        |   62|
|grDevices    |   33|
|plyr         |   25|
|lattice      |   12|
|methods      |   11|
|cluster      |    8|
|reshape      |    7|
|scales       |    7|
|plotrix      |    5|
|sp           |    5|
|compositions |    4|
|grid         |    4|
|stringr      |    4|
|Hmisc        |    3|
|markovchain  |    3|
|farver       |    2|
|RColorBrewer |    2|
|utils        |    2|
|xtable       |    2|
|digest       |    1|
|Gmedian      |    1|
|MASS         |    1|
```

**Comment by dylanbeaudette** [comment]
Consider using `stringi` vs `stringr`.

**Comment by dylanbeaudette** [comment]
Loading `aqp` 1.17.09 takes almost 4 seconds, this is mostly related to the dependencies of `Hmisc`.

![image](https://user-images.githubusercontent.com/624277/67901517-3b12e800-fb24-11e9-9fe5-33367f49ea27.png)

![image](https://user-images.githubusercontent.com/624277/67901526-40703280-fb24-11e9-8a0e-f43b54ba513d.png)

`Hmisc` is only used by `slab`, where `hdquantile` is used over `stats::quantile`. This was selected many years ago due to the _apparent_ improvements over the base estimator when the number of observations were low and there were many ties. The increased complexity of the HD quantile estimator and dependency heft are not worth the benefits.

**Comment by pierreroudier** [comment]
Agreed.

If need be there is still the option to:
- Add an option `hdq`
- test if `Hmisc` is installed
- if so use `Hmisc::hdquantile` in the code

**Comment by dylanbeaudette** [comment]
Thanks Pierre. I'm trying to figure out how to add that option without adding `Hmisc` into SUGGESTS / IMPORTS.

The differences are small, but important--especially when the number of observations per group are small and there are many ties. This is pretty common when working with field observations.

An example, using the `loafercreek` sample data (`soilDB` package).
![image](https://user-images.githubusercontent.com/624277/67902985-b033ec80-fb27-11e9-8321-7e994eee4c82.png)

The HD estimator is certainly smoother (it is based on the bootstrap, so that makes sense) but has higher data requirements than `stats::quantile` and "cleaner" looking lines are well below the level of precision available in field data. They do look "nicer".

@brownag @smroecker what do you guys think?

**Comment by dylanbeaudette** [comment]
After the last commit, `aqp` loads in under 1 second. There are still too many dependencies but this is a little better.

**Comment by brownag** [comment]
I agree that the hdquantiles approach produces a smoother looking line. 

If I had my choice, I would be erring on the side of less smoothing -- and using the stats::quantile approach. I think folks are "impressed" by smooth lines, whereas there is actually a lot of granularity in the data. As nice as the 1cm-slab-wise quantile/median plots are, I think that it is important not to overinterpret them.

I do like that the 25-75th interval is wider for the horizons with less data available using the hdquantile method. Aside from that, I see little practical difference between methods in the IQR or median value coming from the above plot.

**Comment by dylanbeaudette** [comment]
As outlined in #114, and pending discussion moving to `data.table` for all large object processing, grouped aggregation, and reshaping would remove dependencies for:
 * `plyr`
 * `reshape`

**Comment by dylanbeaudette** [comment]
#157 now covers this issue, closing.
