### ISSUE TITLE
"demote" a site-level grouping variable to horizon

### ISSUE THREAD

**Issue by brownag** [ncss-tech/aqp#83]
Say you have a site-level grouping factor, but you would like to be able to make use of that variable in a way such that it is 1:1 with horizons. 

Currently you can achieve this by taking apart and re-assembling the SPC... or making use of a join operation that cleanly handles the many:one relationship. 

For instance, from the loafercreek demo, sec 3.4.7.2 http://ncss-tech.github.io/AQP/demos/profileApply/loafercreek.html#347_range_in_maximum_clay_by_group

```
# create a horizon level redness grouping factor from site
loafercreek$redness <- merge(horizons(loafercreek), 
                            site(loafercreek)[,c('peiid','redness.class')], 
                            all.x = TRUE)$redness.class
```

There should be an easier syntax for this, such as:

```
loafercreek$redness <- horizonGroupFromSite(loafercreek, site.attr='redness.class')
```

Note I'm not particularly attached to that function name, but it is connotative of what it does.

**Comment by dylanbeaudette** [comment]
This sounds similar to the process of [denormalization](https://en.wikipedia.org/wiki/Denormalization).

Options:
   * `denorm` (too close to `dnorm`)
   * `denormalize` (hmmm)
   * `demote` (sounds sad)
   * ???

The function would be incredibly simple.

```r
library(soilDB)

data(loafercreek)


denormalize <- function(obj, attr) {
  
  # extract relevant pieces
  h <- horizons(obj)
  s <- site(obj)
  idn <- idname(obj)
  
  # varibles required for join
  vars <- c(idn, attr)
  
  # perform left-join
  # retain only IDs on left side, IDs + attr on the right
  res <- merge(h[, idn, drop=FALSE], s[, vars], all.x = TRUE)
  
  # susbet named attr
  res <- res[[attr]]
  
  return(res)
}

loafercreek$hz.x <- denormalize(loafercreek, 'x')
```

Testing / documentation / etc. pending.

**Comment by brownag** [comment]
Agreed demote sounds sad / bad. 

And denormalization does seem like the right database-word to describe the process.

I can write the doc and tests, looks like the sample code provided is essentially what I had in mind, and has the correct constraints `drop=FALSE` `all.x=TRUE` for the join

**Comment by brownag** [comment]
Is there value in being able to do denormalize in the other direction?

e.g. `denormalize.hz()` which a site-level value down to horizon.

I guess we already ahve that.

`profileApply()` is essentially the inverse -- in that it allows you to access the horizons of each profile and return an aggregation of that using an arbitrary function. 

In most cases, with simplify=T, you are expecting a result 1:1 with site.

**Comment by brownag** [comment]
Dylan also reminded (informed?) me of the horizon->site denormalization already available via a formula interface

```
site(sp1) <- ~ group
```
