### ISSUE TITLE
more informative errors when subsetting SPCs

### ISSUE THREAD

**Issue by brownag** [ncss-tech/aqp#84]
For instance, this error message is not informative and should direct the user to the unique way that SPC sub-setting works. 

I.e. it looks like a data.frame but if you want it to behave like a data.frame, you need to turn it into one.

```
> target_ids <- my.spc[,idname(my.spc)]
Error: NA not permitted in horizon/slice index
In addition: Warning message:
In .local(x, i, j, ...) : NAs introduced by coercion
```

Of course, since `my.spc` is a SoilProfileCollection, the second index is for _horizon_ not for columns in the site table. Rather than attempting to subset, and producing NAs the SPC should recognize a column name from `siteNames()` or `horizonNames()` was supplied, where a horizon/row-index was expected. 

I am not suggesting dual-functionality, just that the error should reflect what is actually happening.

The correct (unambiguous) syntax is:

```
target_ids <- site(my.spc)[,idname(my.spc)]
```

EDIT: or, of course
```
target_ids <- profile_id(my.spc)
```

**Comment by dylanbeaudette** [comment]
There are some options here
```
# these are the same
profile_id(my.spc)
site(my.spc)[[idname(my.spc)]]
```

The `data.frame` analogy breaks down somewhat because:
   * profile index via `[i, ]`
   * horizon / slice index via `[, j]`

You can't (currently) use `j` to index site/horizon level attributes because they are in different places. I know that the `j` index isn't used all that often. Would it make more sense to use `SPC[i, j, k]` such that:

   * `i` profile indexing
   * `j` horizon indexing
   * `k` attribute indexing

All possible, just requires time and testing.

**Comment by brownag** [comment]
As discussed, my issue was not as much to do with the code example given (`profile_id()` is what I wanted) but rather has to do with more informative error messages.

A simple fix for this would just be to return an error stating that a numeric horizon index is expected. Instead of saying `NA` is not allowed. It is confusing for new users as the `NA` results from the internal SPC method converting the index.

I probably would make use of the `k` index if we ever wanted to take the time to implement it. 

Again: "I am not suggesting dual-functionality [i.e. subsetting by attribute name from the SPC square brackets], just that the error should reflect what is actually happening."

**Comment by dylanbeaudette** [comment]
Relevant code:

```r
# check for missing i and j
  	if(missing(i) & missing(j))
  		stop('must provide either a profile index or horizon/slice index, or both', call.=FALSE)
  	
  	# convert to integer
  	if(!missing(i)) {
  	  if(any(is.na(i)))
  	    stop('NA not permitted in profile index', call.=FALSE)
      # convert logical to integer per standard vector/list indexing rules (thanks Jos? Padarian for the suggestion!)
  	  if(is.logical(i)) i <- (1:length(x))[i]
  	  i <- as.integer(i)
  	}
    else # if no index is provided, the user wants all profiles
      i <- 1:length(x)

    # sanity check
    if(!missing(j)) {
      j <- as.integer(j)
      if(any(is.na(j)))
      stop('NA not permitted in horizon/slice index', call.=FALSE)
    }
```

**Comment by brownag** [comment]
Added the same sort of logical -> integer conversion for horizon index. I have been bitten by the lack of that behavior.

Also added testing/handling for potential non-numeric, non-coercible values in the site or horizon/slice index.

d0484cc
