### ISSUE TITLE
calibrated photo overlay

### ISSUE THREAD

**Issue by dylanbeaudette** [ncss-tech/aqp#91]
As suggested by Nate Looker.

![image](https://user-images.githubusercontent.com/624277/54629944-ec518b80-4a35-11e9-826e-a92eecea4da1.png)

**Comment by pierreroudier** [comment]
So nice.

**Comment by dylanbeaudette** [comment]
Bump, and reminder that the {magick} package, some depth-scaling, and a little plumbing are all that is required here.

**Comment by dylanbeaudette** [comment]
Of course, forgot about that. I'll close this issue, as the "problem" is better addressed with something that already exists. We can move further ideas to the issues / discussion there. Thanks!
