### ISSUE TITLE
normalize line endings

### ISSUE THREAD

**Issue by dylanbeaudette** [ncss-tech/aqp#92]
https://help.github.com/en/articles/dealing-with-line-endings

**Comment by brownag** [comment]
Do we need to be more consistent about setting the relevant options in RStudio (or any other IDE) to minimize any unintentional changes to line endings? 

![image](https://user-images.githubusercontent.com/20842828/86624863-f2e07b00-bf78-11ea-9fbb-a33798288020.png)

This is perhaps part of the problem... but knowing which line ending to use is the bigger issue. Git can handle most of this if we set it up correctly. What is our "normalization" target? Using a .gitattributes file as you set up in AQP is the way to enforce this. Git to choosing via `text=auto`  might not be working out for us: possibly leads to the problems we have with all/most lines in files showing up as "changed" in a commit if the line ending type changes.

Currently we use `text=auto` but should we pick a specific target mode for source files?

We could try defaulting to `text eol=crlf` -- to enforce Windows-like behavior even when source is edited on OSX / Linux [or vice versa]. Then we could just say that when developing for aqp package then you should ensure all source files end with newline and use Windows line endings  (or whatever we decide is standard)

Are there any instances in the aqp package that specifically rely on a particular line ending? I could imagine it being an issue if we had specific build scripts for specific platforms or something like that -- but most if not everything should be platform ambivalent, right?

**Comment by dylanbeaudette** [comment]
I'd prefer to standardize on LF EOL marker if at all possible. I suspect that Travis (linux-based) is barfing on the CRLF EOL marker.

**Comment by brownag** [comment]
Yep -- I am leaning towards the same. Ill have it figured out -- I was catching some Rdas.

Looks like Travis doesnt really care either way about most things. Every error so far has been related to the binary files. There is a check in the build for ensuring LF in makefiles/batch scripts etc that need it, I believe.

**Comment by brownag** [comment]
OK, with 7cba0c2 the binary files are no longer being corrupted when the repo is cloned fresh.

The CRLF -> LF conversion is implicit in the functioning of Git -- so it was redundant to use `text eol=lf` (as we decided on). Furthermore, the * was treating binary files to text even where explict rules were already present. I think the ordering was relevant -- and I had it in the wrong order originally. 

Now in .gitattributes we explicitly define a bunch of text/binary file extensions explicitly and do no use any general pattern that hits binary files too. This was a bit of a head scratcher for me -- and I didn't adequately test it in the case where the repo binary files were created anew.

All developers should set their RStudio options to use LF line endings to minimise generation of warnings about CRLF->LF conversion when working on Windows.

**Comment by brownag** [comment]
Since we have chosen to use LF line endings it might be wise to set up our Git global options to convert any CRLF to LF on commit.

I have noticed I still get some warnings about LF conversions even with .gitattributes in place and my Rstudio settings set. I think some programs (e.g. Notepad on Windows) will introduce CRLF and there may be other ways it happens too.

Will ensure that if a file is created with CRLF that the line endings are converted to LF on commit. I think the default behav
`git config --global core.autocrlf input`
