### ISSUE TITLE
promote tibble to SPC

### ISSUE THREAD

**Issue by dylanbeaudette** [ncss-tech/aqp#94]
Does this work as expected? Anecdotal evidence suggests that it may not.

**Comment by dylanbeaudette** [comment]
Ideas c/o @pierreroudier 

https://stackoverflow.com/questions/35642191/tbl-df-with-s4-object-slots/36117943#36117943

Ideally, we can implement something cleaner than `as.data.frame(object)`.

**Comment by brownag** [comment]
This issue was closed with merge of PR #142
